package com.ibm.btt.application.op.g016;
import java.util.ArrayList;
import java.util.List;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/06/03 17:02:43
 */
public class G016_UC15_Op extends BTTServerOperation {
  private List<String> cardName = new ArrayList<String>();
  private List<String> cardImage = new ArrayList<String>();
  private List<List<String>> cardAdvantages = new ArrayList<List<String>>();
	
	
  public void execute() throws Exception {
	  initializeProduct();
	  Context context=this.getContext();
	  for(int i=0;i<2;i++){
		  context.setValueAt("cards."+i+".image", cardImage.get(i));
		  context.setValueAt("cards."+i+".name", cardName.get(i));
			  
		  context.setValueAt("cards."+i+".advantages.one", cardAdvantages.get(i).get(0));
		  context.setValueAt("cards."+i+".advantages.two", cardAdvantages.get(i).get(1));
		  context.setValueAt("cards."+i+".advantages.three", cardAdvantages.get(i).get(2));
	  }
	  this.fireExitEvent("opEvt");
  }
  
  private void initializeProduct(){
	  cardName.add("Visa Hop!");
	  cardName.add("Iberia Max");
	  
	  cardImage.add("img/G016/imgs/cards/1.jpg");
	  cardImage.add("img/G016/imgs/cards/2.gif");
	  
	  List<String> cardAdvantage1=new ArrayList<String>();
	  cardAdvantage1.add("Free of charge for the first year ");
	  cardAdvantage1.add("Accident insurance of up to ву180,000 ");
	  cardAdvantage1.add("Deferred payment method ");
	  
	  List<String> cardAdvantage2=new ArrayList<String>();
	  cardAdvantage2.add("Free of charge for the first year ");
	  cardAdvantage2.add("Deferred payment method ");
	  cardAdvantage2.add("Internal and external direct debits ");
	  
	  cardAdvantages.add(cardAdvantage1);
	  cardAdvantages.add(cardAdvantage2);
	 
  }
}
