package com.ibm.btt.application.op.g016;
import java.util.ArrayList;
import java.util.List;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/05/22 14:22:47
 */
public class G016_common_Op extends BTTServerOperation {
  private List<String> productName = new ArrayList<String>();
  private List<String> requiredPoints = new ArrayList<String>();
  private List<String> productImageURL = new ArrayList<String>();
  private List<String> countrys = new ArrayList<String>();
  private List<Integer> countryNameNumber = new ArrayList<Integer>();
  private List<String> productSpecialName = new ArrayList<String>();
  private String[][][] forTableTest=new String[4][4][3];
  
  private int productAmount = 4;
  
  public void execute() throws Exception {
	  this.initializeProduct();
	  
	  Context context =this.getContext();
	  //for outside of repetitive panel
	  context.setValueAt("LabelValue", " 2. Gift catalogue");
	  context.setValueAt("Image", "img/G016/imgs/repetitive/fondo-h1-pa_a.gif");
	  
	  int x=0;
	  int y=0;
	  //for inside of repetitive panel
	  for(int i=0 ; i < productAmount; i++){
		  context.setValueAt("products."+i+".ProductName", this.productName.get(i));
		  context.setValueAt("products."+i+".CountrySelction", this.countrys.get(i));
		  context.setValueAt("products."+i+".CountrySelctionNumber", 3-i);
		  context.setValueAt("products."+i+".ProductImageURL", this.productImageURL.get(i));
		  context.setValueAt("products."+i+".RequiredPoints", this.requiredPoints.get(i));
		  context.setValueAt("products."+i+".ProductSpecialName", this.productSpecialName.get(i));
		  for(int j=0;j<4;j++){
			  
			  context.setValueAt("products."+i+".ForTableTest."+j+".A", forTableTest[i][j][0]);
			  context.setValueAt("products."+i+".ForTableTest."+j+".B", forTableTest[i][j][1]);
		  }
		  
		  for(int j=0 ; j < 4 ;j++){
			  context.setValueAt("products."+i+".Countrys."+j+".CountryName", this.countrys.get(j));
			  context.setValueAt("products."+i+".Countrys."+j+".CountryNameNumber", this.countryNameNumber.get(j));
		  }
		  //For UC12
		  if(i%2==0){
			  context.setValueAt("productsGroup1."+x+".ProductName", this.productName.get(i));
			  context.setValueAt("productsGroup1."+x+".ProductImageURL", this.productImageURL.get(i));
			  context.setValueAt("productsGroup1."+(x++)+".RequiredPoints", this.requiredPoints.get(i));
		  }else{
			  context.setValueAt("productsGroup2."+y+".ProductName", this.productName.get(i));
			  context.setValueAt("productsGroup2."+y+".ProductImageURL", this.productImageURL.get(i));
			  context.setValueAt("productsGroup2."+(y++)+".RequiredPoints", this.requiredPoints.get(i));
			  
		  }
	  }
	  
	  this.fireExitEvent("opEvt");
  }
  
  private void initializeProduct(){
	  productName.add("DESTORNILLADOR KC9024 BLACK AND DECKER");
	  productName.add("JUEGO DE PYREX DE 5 PIEZAS ");
	  productName.add("CRISTALERÍA D`ARQUES ");
	  productName.add("CAFETERA ALICIA DELONGHI");
	  
	  requiredPoints.add("660 puntos");
	  requiredPoints.add("100 puntos");
	  requiredPoints.add("200 puntos");
	  requiredPoints.add("200 puntos");
	  
	  productImageURL.add("img/G016/imgs/repetitive/1.jpg");
	  productImageURL.add("img/G016/imgs/repetitive/2.jpg");
	  productImageURL.add("img/G016/imgs/repetitive/3.jpg");
	  productImageURL.add("img/G016/imgs/repetitive/4.jpg");
	  
	  countrys.add("Russia");
	  countrys.add("China");
	  countrys.add("Spain");
	  countrys.add("England");
	  
	  countryNameNumber.add(0);
	  countryNameNumber.add(1);
	  countryNameNumber.add(2);
	  countryNameNumber.add(3);
	  
	  productSpecialName.add("new tools");
	  productSpecialName.add("gless");
	  productSpecialName.add("juicer (new)");
	  productSpecialName.add("lunch-box");
	  
	  //test table in repetitive panel
	  for(int i=0;i<4;i++){
		  for(int j=0;j<4;j++){
			  for(int k=0;k<3;k++){
				  forTableTest[i][j][k]=i+"-"+j+"-"+k;
			  }
		  }
	  }
	  
  }
  	
}
