package com.ibm.btt.application.op.g016;
import java.util.ArrayList;
import java.util.List;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/05/17 13:43:09
 */
public class G016_Function_test_Op extends BTTServerOperation {
  
  int repetitivePanelListSize=4;
  private List<String> productName = new ArrayList<String>();
  private List<String> requiredPoints = new ArrayList<String>();
  private List<String> countrys = new ArrayList<String>();
  private List<Integer> countrysNumber = new ArrayList<Integer>();
  private String[][][] forTableTest=new String[4][4][4];
  
  public void execute() throws Exception {
	  initializeProduct();
	  Context context = this.getContext();
	  context.setValueAt("Image", "img/G016/imgs/repetitive/fondo-h1-pa_a.gif");
	  context.setValueAt("LabelValue", " 2.Global label");
	 
	  for(int i=0; i< repetitivePanelListSize ;i++){
		  context.setValueAt("Countrys."+i+".CountryName", this.countrys.get(i));
		  context.setValueAt("Countrys."+i+".CountryNameNumber", this.countrysNumber.get(i));
		  context.setValueAt("G016_Function_Test_List."+i+".Inner_Image", "img/G016/imgs/repetitive/010251.jpg");
		  context.setValueAt("G016_Function_Test_List."+i+".ProductName", this.productName.get(i));
		  context.setValueAt("G016_Function_Test_List."+i+".RequiredPoints", this.requiredPoints.get(i));
		  
		  for(int j=0;j<4;j++){
			  
			  context.setValueAt("G016_Function_Test_List."+i+".TestTable."+j+".A", forTableTest[i][j][0]);
			  context.setValueAt("G016_Function_Test_List."+i+".TestTable."+j+".B", forTableTest[i][j][1]);
			  context.setValueAt("G016_Function_Test_List."+i+".TestTable."+j+".C", forTableTest[i][j][2]);
			  context.setValueAt("G016_Function_Test_List."+i+".TestTable."+j+".D", forTableTest[i][j][3]);
			  context.setValueAt("G016_Function_Test_List."+i+".TestTable."+j+".CountrysResult", j);
		  }
	  }
	  
	 fireExitEvent("opEvt");
  }
  
  private void initializeProduct(){
	  productName.add("DESTORNILLADOR KC9024 BLACK AND DECKER");
	  productName.add("JUEGO DE PYREX DE 5 PIEZAS ");
	  productName.add("CRISTALERÍA D`ARQUES ");
	  productName.add("CAFETERA ALICIA DELONGHI");
	  
	  requiredPoints.add("660 puntos");
	  requiredPoints.add("100 puntos");
	  requiredPoints.add("200 puntos");
	  requiredPoints.add("200 puntos");
	  
	  countrys.add("Russia");
	  countrys.add("China");
	  countrys.add("Spain");
	  countrys.add("England");
	  
	  countrysNumber.add(0);
	  countrysNumber.add(1);
	  countrysNumber.add(2);
	  countrysNumber.add(3);
	  //test table in repetitive panel
	  for(int i=0;i<4;i++){
		  for(int j=0;j<4;j++){
			  for(int k=0;k<4;k++){
				  forTableTest[i][j][k]=i+"-"+j+"-"+k;
			  }
		  }
	  }
  }
}
