package com.ibm.btt.banco.operation;
import com.ibm.btt.base.BTTServerOperation;
/** 
 * Class Generated by BTT Tool
 * Created since: 2010/09/29 10:51:29
 */
public class FilterText extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  System.out.println("-----Call ajax operation FilterText begin");
	  
	  String text = (String) getValueAt("inputText");
	  String richText = (String) getValueAt("inputRichText");
	  String textArea = (String) getValueAt("inputTextArea");
	  
	  setValueAt("filterText", text.replace("gcd", ""));
	  setValueAt("filterRichText", richText.replace("gcd", ""));
	  setValueAt("filterTextArea", textArea.replace("gcd", ""));
	  
	  System.out.println("-----Call ajax operation FilterText begin");
  }
}
