package com.ibm.btt.banco.operation;
import com.ibm.btt.base.BTTServerOperation;
/** 
 * Class Generated by BTT Tool
 * Created since: 2010/09/27 16:05:49
 */
public class GetCitiesByProvince extends BTTServerOperation {
  /** 
 * <!-- begin-uselr-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  	System.out.println("Operation GetCitiesByProvince executed...");
	  
		String provice = (String) getValueAt("provice");
		if ("hubei".equalsIgnoreCase(provice) || "Hu Bei".equalsIgnoreCase(provice)) {
			setValueAt("iCityList.0.label","Wu Han");
			setValueAt("iCityList.0.value","wuhan");			
			setValueAt("iCityList.1.label","Chi Bi");
			setValueAt("iCityList.1.value","chibi");
			setValueAt("iCityList.2.label","Jing Zhou");
			setValueAt("iCityList.2.value","jingzhou");
		} else if ("henan".equalsIgnoreCase(provice) || "He Nan".equalsIgnoreCase(provice)) {
			setValueAt("iCityList.0.label","An Yang");
			setValueAt("iCityList.0.value","anyang");			
			setValueAt("iCityList.1.label","Zheng Zhou");
			setValueAt("iCityList.1.value","zhengzhou");
			setValueAt("iCityList.2.label","Luo Yang");
			setValueAt("iCityList.2.value","luoyang");
		} 
  }
}
