package com.ibm.btt.banco.operation;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.cs.html.HtmlConstants;
/** 
 * Class Generated by BTT Tool
 * Created since: 2010/09/16 15:45:21
 */
public class HFormInitOp extends BTTServerOperation {
	protected final String PAGENAME = "pageName";
	public void execute() throws Exception {
		setValueAt("iProvinceList.0.label","Hu Bei");
		setValueAt("iProvinceList.0.value","hubei");			
		setValueAt("iProvinceList.1.label","He Nan");
		setValueAt("iProvinceList.1.value","henan");
		
		setValueAt(HtmlConstants.REPLYPAGE, getValueAt(PAGENAME));
	}
}
