package com.ibm.btt.banco.operation;
import com.ibm.btt.automaton.ext.DSEOperationState;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Hashtable;
import com.ibm.btt.base.OperationRepliedEvent;
/** 
 * Class Generated by BTT Tool
 * Created since: 2011/03/15 10:38:13
 */
public class InitRecordPage extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  OperationRepliedEvent event = new OperationRepliedEvent(this);
	  Hashtable ht = new Hashtable();
	  event.setParameters(ht);
	  
	  ht.put(DSEOperationState.EXIT_EVENT_NAME, "ok");
	  
	  System.out.println(this.getContext().getParent().getParent().getKeyedCollection());
	  
	  this.fireHandleOperationRepliedEvent(event);
  }
}
