package com.ibm.btt.application.op.B001;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;

/**
 * Class Generated by BTT Tool Created since: 2013/09/10 11:00:45
 */
public class MyCreditAcctsOp extends BTTServerOperation {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {
		Context c = this.getContext();
		KeyedCollection k = c.getKeyedCollection();
		IndexedCollection myCreditAccts = (IndexedCollection) k
				.getElementAt("MyCreditAccts");
		myCreditAccts.removeAll();
		KeyedCollection creditAcct0 = new KeyedCollection();
		creditAcct0.setDynamic(true);
		creditAcct0.setName("CreditAcct");
		creditAcct0.setValueAt("GivenName", "Golden Card");
		creditAcct0.setValueAt("AcctNo", "4367 4800 0679 1738");
		creditAcct0.setValueAt("BranchBank", "BeiJing Branch");
		creditAcct0.setValueAt("ParentType", "Multi-Currency");
		creditAcct0.setValueAt("CurBalanceList.0.CurType", "RMB");
		creditAcct0.setValueAt("CurBalanceList.0.CreditLine", (double)5000.00);
		creditAcct0.setValueAt("CurBalanceList.0.WithdrawalLine", (double)2000.00);
		creditAcct0.setValueAt("CurBalanceList.0.AvailableCredit", (double)8000.00);
		creditAcct0.setValueAt("CurBalanceList.0.Balance", (double)3000.00);
		creditAcct0.setValueAt("CurBalanceList.1.CurType", "USD");
		creditAcct0.setValueAt("CurBalanceList.1.CreditLine", (double)1899.00);
		creditAcct0.setValueAt("CurBalanceList.1.WithdrawalLine", (double)1899.00);
		creditAcct0.setValueAt("CurBalanceList.1.AvailableCredit", (double)2300.00);
		creditAcct0.setValueAt("CurBalanceList.1.Balance", (double)1500.00);

		KeyedCollection creditAcct1 = new KeyedCollection();
		creditAcct1.setDynamic(true);
		creditAcct1.setName("CreditAcct");
		creditAcct1.setValueAt("GivenName", "Single-Currency");
		creditAcct1.setValueAt("AcctNo", "4367 4800 2395 1414");
		creditAcct1.setValueAt("BranchBank", "BeiJing Branch");
		creditAcct1.setValueAt("ParentType", "RMB 	");
		creditAcct1.setValueAt("CurBalanceList.0.CurType", "RMB");
		creditAcct1.setValueAt("CurBalanceList.0.CreditLine", (double)2400.00);
		creditAcct1.setValueAt("CurBalanceList.0.WithdrawalLine", (double)4890.00);
		creditAcct1.setValueAt("CurBalanceList.0.AvailableCredit", (double)3000.00);
		creditAcct1.setValueAt("CurBalanceList.0.Balance", (double)2600.00);

		
		KeyedCollection creditAcct2 = new KeyedCollection();
		creditAcct2.setDynamic(true);
		creditAcct2.setName("CreditAcct");
		creditAcct2.setValueAt("GivenName", "Euro Card");
		creditAcct2.setValueAt("AcctNo", "4367 4812 3498 7656");
		creditAcct2.setValueAt("BranchBank", "BeiJing Branch");
		creditAcct2.setValueAt("ParentType", "Multi-Currency");
		creditAcct2.setValueAt("CurBalanceList.0.CurType", "RMB");
		creditAcct2.setValueAt("CurBalanceList.0.CreditLine", (double)10000.00);
		creditAcct2.setValueAt("CurBalanceList.0.WithdrawalLine", (double)5000.00);
		creditAcct2.setValueAt("CurBalanceList.0.AvailableCredit", (double)9000.00);
		creditAcct2.setValueAt("CurBalanceList.0.Balance", (double)1000.00);
		creditAcct2.setValueAt("CurBalanceList.1.CurType", "Euro");
		creditAcct2.setValueAt("CurBalanceList.1.CreditLine", (double)2000.00);
		creditAcct2.setValueAt("CurBalanceList.1.WithdrawalLine", (double)500.00);
		creditAcct2.setValueAt("CurBalanceList.1.AvailableCredit", (double)1500.00);
		creditAcct2.setValueAt("CurBalanceList.1.Balance", (double)2000.00);
		
		myCreditAccts.addElement(creditAcct0);
		myCreditAccts.addElement(creditAcct1);
		myCreditAccts.addElement(creditAcct2);
		
		fireExitEvent("opEvt");
	}
	
}
