package com.ibm.btt.application.op.B001;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.test.util.CreditPointDB;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/09/10 16:03:37
 */
public class QueryPointsOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  KeyedCollection k = this.getContext().getKeyedCollection();
	  Integer selectRowNum = (Integer) k.getValueAt("RowNum");
//	  System.out.println(selectRowNum);
//	  System.out.println("KF = " + k.getValueAt("KF"));
	  IndexedCollection myCreditAccts = (IndexedCollection) k.getElementAt("MyCreditAccts");
	  IndexedCollection myPoints = (IndexedCollection) k.getElementAt("MyPoints");
	  myPoints.removeAll();
	  IndexedCollection pointInDB = CreditPointDB.getInstance().getAllCreditPoint();
	  if(selectRowNum != null){
		  KeyedCollection myCreditAcct = (KeyedCollection) myCreditAccts.getElementAt(selectRowNum);
		  //query credit point info
		  String acctNo = (String) myCreditAcct.getValueAt("AcctNo");
		  for(int j = 0; j < pointInDB.size(); j ++){
			  String acctNo2 = (String) pointInDB.getValueAt(j + ".AcctNo");
			  if (acctNo.equals(acctNo2)){
				  KeyedCollection creditPoint = (KeyedCollection) pointInDB.getElementAt(j);
				  KeyedCollection point = new KeyedCollection();
				  point.setDynamic(true);
				  point.setName("MyPoint");
				  //set acct info
				  point.setValueAt("GivenName", myCreditAcct.getValueAt("GivenName"));
				  point.setValueAt("AcctNo", myCreditAcct.getValueAt("AcctNo"));
				  point.setValueAt("BranchBank", myCreditAcct.getValueAt("BranchBank"));
				  point.setValueAt("ParentType", myCreditAcct.getValueAt("ParentType"));
				  // set credit point info
				  point.setValueAt("AcctType", creditPoint.getValueAt("AcctType"));
				  point.setValueAt("BalancePoints",creditPoint.getValueAt("BalancePoints"));
				  point.setValueAt("ConsumptionPoints", creditPoint.getValueAt("ConsumptionPoints"));
				  point.setValueAt("RewardPoints", creditPoint.getValueAt("RewardPoints"));
				  myPoints.addElement(point);
			  }
		  }
	  }
	  fireExitEvent("opEvt");
  }
}
