package com.ibm.btt.application.op.B001;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.test.util.BillDB;
import com.ibm.btt.test.util.PaginationUtilForTest;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/09/11 23:13:59
 */
public class QuerySettledBillOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  KeyedCollection k = getContext().getKeyedCollection();
	  KeyedCollection paginationData = (KeyedCollection) k.getElementAt("paginationData");
	  IndexedCollection settledBillList = (IndexedCollection) k.getElementAt("SettledBillList");
	  Context flowContext = getContext().getParent();
	  // get the selected acctno
	  String selectedAcctNo = (String) flowContext.getKeyedCollection().getValueAt("Bill.AcctNo");
	  // get all the unsettled bill from db
	  IndexedCollection allUnsettledBill = BillDB.getInstance().getAllBill();
	  // get the search condition from flow
	  KeyedCollection searchCondition = (KeyedCollection) flowContext.getKeyedCollection().getElementAt("SearchCondition");
	  String condition_curType = (String) searchCondition.getValueAt("CurType");
	  String condition_period = (String) searchCondition.getValueAt("TimePeriod");
	  IndexedCollection temp = new IndexedCollection();
	  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	  temp.removeAll();
	  for (int i = 0; i < allUnsettledBill.size(); i++){
			KeyedCollection bill = (KeyedCollection) allUnsettledBill.getElementAt(i + "");
			if (selectedAcctNo != null && !bill.getValueAt("AcctNo").toString().equals(selectedAcctNo)){
				continue;
			}
			if(condition_curType != null && !bill.getValueAt("CurType").toString().contains(condition_curType)){
				continue;
			}
			// There's only 2012's bill, so I will not take care of the 2013's bill.
			Date tradeDate = (Date) bill.getValueAt("TradeDate");
			String tradeDateStr = sdf.format(tradeDate);
			int tradeMonth = Integer.parseInt(tradeDateStr.substring(5, 7));
			int tradeDay = Integer.parseInt(tradeDateStr.substring(8, 10));
			
			if (tradeDay < 18){
				tradeMonth --;
			}
			if( condition_period != null && Integer.parseInt(condition_period) != tradeMonth ){
				continue;
			}
			temp.addElement(bill);
		}
	  settledBillList = PaginationUtilForTest.paginateTheIColl(paginationData, temp, settledBillList);
	  fireExitEvent("opEvt");
  }
}
