package com.ibm.btt.application.op;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;

/**
 * Class Generated by BTT Tool Created since: 2013/01/16 18:07:15
 */
public class RestChannelOp extends BTTServerOperation {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {
		Context context = super.getContext();
		context.setValueAt("numberDataSe", 122);

		System.out.println("*************************************************");
		System.out.println(context);
		System.out.println("*************************************************");
		System.out.println("start execute");
		fireExitEvent("opEvt");
		System.out.println("end execute");
	}

}
