package com.ibm.btt.application.op;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.rest.test.DataValue;

/**
 * Class Generated by BTT Tool Created since: 2013/01/16 18:07:15
 */
public class RestChannelOp extends BTTServerOperation {

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {
		Context context = this.getContext();
		Context cxtSuper = context.getParent();
		DataValue dv = new DataValue();
		cxtSuper.setValueAt("numberDataSe", dv.getNumberValue());
		cxtSuper.setValueAt("stringDataSe", dv.getStringValue());
		cxtSuper.setValueAt("dateDataSe", dv.getDateValue());
		cxtSuper.setValueAt("currencyDataSe", dv.getCurrencyValue());
		cxtSuper.setValueAt("booleanDataSe", dv.getBooleanValue());
//		cxtSuper.setValueAt("byteArrayDataSe", dv.getByteArrayValue() );
		cxtSuper.setValueAt("byteDataSe", dv.getByteValue());
		cxtSuper.setValueAt("shortDataSe", dv.getShortValue());
		cxtSuper.setValueAt("integerDataSe", dv.getIntValue());
		cxtSuper.setValueAt("longDataSe", dv.getLongValue());
		cxtSuper.setValueAt("FloatDataSe", dv.getFloatValue());
		cxtSuper.setValueAt("doubleDataSe", dv.getDoubleValue());
//		cxtSuper.setValueAt("XMLGregorianCalendarDataSe", DataValue.convertToXMLGregorianCalendar());
//		cxtSuper.setValueAt("bigIntegerDataSe", dv.getBigIngeterValu());
//		cxtSuper.setValueAt("bigDecimalDataSe", dv.getBigDecimal());

		System.out.println("*************************************************");
		System.out.println(context.getParent().getKeyedCollection().toString());
		System.out.println("*************************************************");
		System.out.println("start execute");
		fireExitEvent("opEvt");
		System.out.println("end execute");
	}

}
