({
"Click_Link_Run_Flow":"Click this link to launch the sample flow",
"Final_Page_Flow":"This is the final page of the sample flow",
"28855note":"Current behavior is that when no dataName is defined for several widgets \r\nthe tool validation produces and Error.There are views were widgets want \r\nto be used but might not need to be bound to data.",
"comboboxMark03":"When clicking the combobox, If the state \r\nof the combobox is the same as the value \r\nof the right label, the label will display\r\nthe state, or will display the opposite \r\nthe state.",
"comboboxMark02":"When clicking the combobox, If the state \r\nof the combobox is the same as the value \r\nof the right label, the widget will display\r\nthe state, or will display the opposite \r\nthe state.",
"tabbedPaneMark02":"welcome",
"textBoxMark03":"if  the value\r\nof textbox \r\nexists and \r\nclick the \r\nbotton, the \r\nerror will\r\nbe displayed",
"sampleW021mark03":"\r\nmulti$pleenters\r\n\r\nMT\#_S&istheIBMapproved8&\!@\#$%^&*()_+\=-\r\nMinternal(\r\n\r\n)networkw",
"tabbedPaneMark01":"Please input your id",
"sampleW021mark02":"MTSistheIBMapprovedmethodforaccessingtheIB\r\nMinternalnetworkwhenworkingremotely.",
"selectListMark03":"When clicking the selectList, If the state \r\nof the selectList is the same as the value \r\nof the right label, the label will display\r\nthe state, or will display the opposite \r\nthe state.",
"textBoxMark02":"When clicking the textBox, if the state \r\nof the textBox is the same as the value \r\nof the right label, the textBox will display\r\nthe state, or will display the opposite \r\nthe state.",
"selectListMark02":"When clicking the selectList, If the state \r\nof the selectList is the same as the value \r\nof the right label, the widget will display\r\nthe state, or will display the opposite \r\nthe state.",
"sampleW021mark01":"MTS is the IBM approved method for accessing the IBM internal network when working remotely.",
"textBoxMark01":"If you trigger the right the event and the\r\nvalue of textbox will change from 1 to 2.",
"Welcome_To_Btt_Sample":"Welcome to BTT sample page",
"selectListMark01":"If you trigger the right the event and the\r\nvalue of label will change from label to success."})
