({
"stock":"Stock",
"Christmas_Club":"Christmas Club",
"currency":"Currency",
"please_input_your_id":"Please input your id",
"fund":"Fund",
"index":"Index",
"amount":"Amount",
"Savings":"Savings",
"per_month":"per month",
"cardNo":"Card Number",
"Checking":"Checking",
"submit":"Submit",
"Money_Market":"Money Market",
"Universal_Card":"Universal Card",
"transaction":"Transaction",
"welcome":"Welcome",
"please_select_your_transaction":"Please Select Your Transaction",
"per_year":"per year"})
