package com.ibm.btt.application.op.X070;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.test.util.CashAccountDB;
import com.ibm.btt.test.util.PaginationUtilForTest;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/07/24 15:11:36
 */
public class X070_UC5_PaginateOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection k = getContext().getKeyedCollection();
	  KeyedCollection paginationData = (KeyedCollection) k.getElementAt("paginationData");
	  IndexedCollection cashAcctList = (IndexedCollection) k.getElementAt("cashAcctList");
	  IndexedCollection allCashAcct = CashAccountDB.getInstance().getAllCashAcct();
	  cashAcctList = PaginationUtilForTest.paginateTheIColl(paginationData, allCashAcct, cashAcctList);
	  fireExitEvent("opEvt");
  }
}
