package com.ibm.btt.application.op.X070;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.test.util.CashAccountDB;

/**
 * Class Generated by BTT Tool Created since: 2013/07/25 09:40:42
 */
public class X070_InitDataOp extends BTTServerOperation {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {
		KeyedCollection k = getContext().getKeyedCollection();
		IndexedCollection cashAcctList = (IndexedCollection) k
				.getElementAt("cashAcctList");
		cashAcctList.removeAll();
		IndexedCollection allCashAcct = CashAccountDB.getInstance()
				.getAllCashAcct();
		if (allCashAcct != null) {
			for (int i = 0; i < 10; i++) {
				cashAcctList.addElement(allCashAcct.getElementAt(i));
			}
		}
		fireExitEvent("opEvt");
	}
}
