package com.ibm.btt.application.op.Q002;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.dojo.model.TreeModel;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/08/06 17:39:34
 */
public class AllWidgetInit extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
 Context context = this.getContext();
	  
	  context.setValueAt("allWidgetRecord.gender",0);
	  context.setValueAt("allWidgetRecord.level.level1",false);
	  context.setValueAt("allWidgetRecord.level.level2",true);
	  context.setValueAt("allWidgetRecord.image","img/G016/imgs/cards/pdf.gif");
	  context.setValueAt("allWidgetRecord.richtext","test richtext");
	  context.setValueAt("allWidgetRecord.textArea","test textArea");
	  context.setValueAt("allWidgetRecord.hiddenField","Hello ~ I'm hiddenField");
	  context.setValueAt("allWidgetRecord.errorMessage","errorMessage test");
	  
	  
	  for(int i=0;i<5;i++){
		  
		  context.setValueAt("allWidgetRecord.combo."+i+".comboLabel","city"+i);
		  context.setValueAt("allWidgetRecord.combo."+i+".comboValue",""+i);
	  }
	  for(int i=0;i<5;i++){
		  
		  context.setValueAt("allWidgetRecord.select."+i+".selectLabel","country"+i);
		  context.setValueAt("allWidgetRecord.select."+i+".selectValue",""+i);
	  }
	  
	  	for (int i = 0; i < 10; i++) {
	  		if (i==2) {
				//select field
	  			context.setValueAt("allWidgetRecord.MultiSelect."+i+".FieldForLabel","Selected is true");
	  			context.setValueAt("allWidgetRecord.MultiSelect."+i+".FieldForSelect","true");
			}else if(i==4){
				//disable filed
				context.setValueAt("allWidgetRecord.MultiSelect."+i+".FieldForLabel","disabled is true");
				context.setValueAt("allWidgetRecord.MultiSelect."+i+".FieldForDisable","true");
				
			}else{
				context.setValueAt("allWidgetRecord.MultiSelect."+i+".FieldForLabel","sample-"+i);
			}
	  		context.setValueAt("allWidgetRecord.MultiSelect."+i+".FieldForValue","value-"+i);
		}
	  	
	  	for(int i=0;i<10;i++){
	  		context.setValueAt("allWidgetRecord.table."+i+".column1","c1-"+i);
	  		context.setValueAt("allWidgetRecord.table."+i+".column2","c2-"+i);
	  		context.setValueAt("allWidgetRecord.table."+i+".column3","c3-"+i);
	  		
	  	}
	  	TreeModel root = (TreeModel) getElementAt("allWidgetRecord.root");
		  root.setLabel("root");
		  TreeModel level1_1 = new TreeModel("level1-1", "002", "level1-1");
		  TreeModel level2_1 = new TreeModel("level2-1", "005", "level2-1");
		  TreeModel level3_1 = new TreeModel("level3-1", "008", "level3-1");
		  level1_1.addChild(level2_1);
		  level1_1.addChild(level3_1);
		  
		  TreeModel level1_2 = new TreeModel("level1-2", "003", "level1-2");
		  TreeModel level2_2 = new TreeModel("level2-2", "006", "level2-2");
		  TreeModel level3_2 = new TreeModel("level3-2", "009", "level3-2");
		  level1_2.addChild(level2_2);
		  level1_2.addChild(level3_2);
		  
		  TreeModel level1_3 = new TreeModel("level1-3", "004", "level1-3");
		  TreeModel level2_3 = new TreeModel("level2-3", "007", "level2-3");
		  level1_3.addChild(level2_3);
		  
		  root.addChild(level1_1);
		  root.addChild(level1_2);
		  root.addChild(level1_3);
	  this.fireExitEvent("opEvt");
  }
}
