package com.ibm.btt.application.op.Q002;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/07/30 16:30:53
 */
public class CheckLoginOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  Context context =this.getContext();
	  String username=(String) context.getValueAt("User.UserName");
	  String password= (String) context.getValueAt("User.UserPassword");
	  if("user".equals(username) && "123".equals(password)){
		  
		  this.fireExitEvent("pass");
	  }else
		  this.fireExitEvent("fail");
  }
}
