package com.ibm.btt.application.op.Q002;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/08/20 16:38:38
 */
public class InitializeTableOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Context context = this.getContext();
	  for(int i=0 ;i<10 ;i++){
		  context.setValueAt("table_List."+i+".filed1","a"+i);
		  context.setValueAt("table_List."+i+".filed2","b"+i);
		  context.setValueAt("table_List."+i+".filed3","c"+i);
	  }
	  this.fireExitEvent("opEvt");
  }
}
