package com.ibm.btt.application.op.B002;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/11/14 17:02:26
 */
public class B002_UC1_Op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  String stateFlag = (String) getValueAt("stateFlag");
	  System.out.println("Boo2_UC1_Op executed, and the stateFlag is " + stateFlag);
	  KeyedCollection k = this.getContext().getKeyedCollection();
	  k.setValueAt("opErrorMessage", "this error message is from B002_UC1_Op");
	  if("SubFlow".equals(stateFlag)) {
		  	setValueAt("errorCode", "0");
			setValueAt("errorMsg", "Error Occurs! handle the error in subflow");
			fireExitEvent("errorHandling_SubFlow");
		}else if("Operation".equals(stateFlag)) {
			setValueAt("errorCode", "1");
			setValueAt("errorMsg", "Error Occurs! handle the error in Operation");
			fireExitEvent("errorHandling_Operation");
		}else if("Page".equals(stateFlag)) {
			setValueAt("errorCode", "2");
			setValueAt("errorMsg", "Error Occurs! Display the error message in Page");
			fireExitEvent("errorHandling_Page");
		}else if("Popup".equals(stateFlag)) {
			setValueAt("errorCode", "3");
			setValueAt("errorMsg", "Error Occurs! Display the error message in Popup");
			fireExitEvent("errorHandling_Popup");
//		}else if("Condition".equals(stateFlag)) {
//			setValueAt("errorCode", "4");
//			setValueAt("errorMsg", "Error Occurs! Display the error message depand on the Condition");
//			fireExitEvent("errorHandling_Condition");
		}else if ("PopupSubFlow".equals(stateFlag)){
			setValueAt("errorCode", "5");
			setValueAt("errorMsg", "Error Occurs! handle the error in PopupFlow");
			fireExitEvent("errorHandling_PopupSubFlow");
		}else{
			setValueAt("errorMsg", "No Error Occurs! It excute successful");
			fireExitEvent("opEvt");
		}
	  
  }
}
