package com.ibm.btt.application.op.B002;
import com.ibm.btt.base.BTTServerOperation;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/11/18 16:42:23
 */
public class B002_UC2_OP extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  System.out.println("this is B002_UC2_Op");
	  fireExitEvent("errorHandling");
  }
}
