package com.ibm.btt.application.op.svt.a8103;
import java.util.HashMap;
import java.util.Map;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.web.service.BTTWSServiceHandlerProxy;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/08/27 13:27:53
 */
public class SVT_ajax_checkuserOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Thread.sleep(1500);
	  Context context =this.getContext();
	  BTTWSServiceHandlerProxy proxy = new BTTWSServiceHandlerProxy(
		"http://localhost:9080/InternetBankTestWeb/services/BTTWSServiceHandler");
		HashMap<String, Object> m = new HashMap<String, Object>();
		m.put("dse_operationName", "svt_8103_for_webservice_Op");
		m.put("username", context.getValueAt("User.UserName"));
		m.put("password", context.getValueAt("User.UserPassword"));
		// filter
		HashMap<String, Object> filterMap = new HashMap<String, Object>();
		filterMap.put("checkUserResult", "");
		m.put("dse_wsResponseFilter", filterMap);
		
		Map<String, Object> resultMap = proxy.callBTT(m);
		System.out.println(resultMap);
		
		 if("pass".equals(resultMap.get("checkUserResult"))){
			  context.setValueAt("checkUserResult","pass");
		  }else{
			  context.setValueAt("checkUserResult","fail");
			  
		  }
  }
}
