package com.ibm.btt.application.op.svt.a8103;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/08/27 18:25:45
 */
public class SVT_8103_for_webserviceOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Context context =this.getContext();
	  System.out.println(context.getValueAt("username"));
	  System.out.println(context.getValueAt("password"));
	  if(User.getUsername().equals(context.getValueAt("username"))&& User.getPassword().equals(context.getValueAt("password"))){
		  context.setValueAt("checkUserResult","pass");
	  }else{
		  context.setValueAt("checkUserResult","fail");
		  
	  }
  }
}
