({
"Reset_Process":"Reinicio del proceso",
"ERROR_in_Server__":"ERROR in Server\: ",
"Only_non-negative_amounts_":"S\u00f3lo valores positivos mayores de cero son aceptados en este campo",
"The_-from_account-_and_-to":"Las cuentas origen y destino no pueden coincidir",
"Payment":"Pago",
"All_amount_values_are_allo":"Cualquier valor es aceptado en este campo",
"Account_Transfer":"Transferencia de fondos",
"You_may_go_back":"Puede retroceder y corregir los datos. Tambi\u00e9n podemos atenderle de manera personal en el tel\u00e9fono <B\>99-9-999-999-9999</B\>, estaremos encantados de ayudarle a realizar su petici\u00f3n.",
"Cannot_provide_service":"Fuera de servicio",
"Only_non-zero_amounts_are_":"S\u00f3lo valores positivos mayores de cero son aceptados en este campo",
"Cancel_credit_card_application":"Cancelar la petici\u00f3n de tarjeta de cr\u00e9dito ",
"The_Platinum_Card":"La tarjeta Platinum",
"Operation_warning":"Notificaci\u00f3n de la operaci\u00f3n\:",
"We_apologize_II":"Sentimos no poder cursar su petici\u00f3n en estos momentos. Por favor, int\u00e9ntelo de nuevo m\u00e1s tarde o seleccione otro servicio del men\u00fa. Los siguientes mensajes han sido obtenidos por la infraestructura\:",
"Only_negative_amounts_are_":"S\u00f3lo valores negativos son aceptados en este campo",
"Please_enter_the_amount_of_the_payment":"Indique la cantidad del pago",
"Use__java_com.ibm.btt.samp":"Use\: java com.ibm.btt.samples.appl.StartServerServlet [-s <server_address\>] [-p <dseIniPath\>] [-h]",
"You_have_selected_to_apply_for_a":"Ha decidido obtener una tarjeta de cr\u00e9dito",
"Occupation":"Cargo",
"Date_of_Birth":"Fecha de nacimiento",
"Exception_in_main_":"Exception in main\:",
"Try_again":"Puede intentarlo de nuevo seleccionando su opci\u00f3n en el men\u00fa. Tambi\u00e9n podemos atenderle de manera personal en el tel\u00e9fono <B\>99-9-999-999-9999</B\>, estaremos encantados de ayudarle a realizar su petici\u00f3n.",
"Please_enter_the_amount_of_money_to_be_transferred":"Indique la cantidad de la transferencia\:",
"Cross_validation_errors_have_occurred":"Han habido errores de validaci\u00f3n cruzada\:",
"Process_my_selection":"Proceder con mi elecci\u00f3n",
"Yes":"S\u00ed",
"___MUST_be_at_least_":"\" MUST be at least  ",
"Cancel_Confirmation":"Confirmaci\u00f3n de cancelaci\u00f3n",
"Account_Summary":"Extracto de cuentas",
"String_validation_error":"String validation error ",
"Amount_transferred":"Cantidad transferida\:",
"Are_you_a_US_citizen_or_a_permanent_US_resident":"Es usted ciudadano de los EEUU o residente?",
"Social_security_numbers_mu":"El n\u00famero de seguridad social no debe contener caracteres no num\u00e9ricos.",
"Type":"Tipo",
"Ignored_field_val_for_income":"Resultado de la validaci\u00f3n ignorado para el campo Ingresos\:",
"Home_Address":"Direcci\u00f3n particular",
"_cannot_be_converted_to_an":"cannot be converted to an Object of Type  ",
"Checking_Account":"Cuenta corriente",
"Select_an_account_TO_which_money_is_deposited":"Seleccione la cuenta destino de la transferencia\:",
"No_amount_values_are_allow":"No se aceptan valores num\u00e9ricos en este campo",
"Middle_Name":"Iniciales",
"Submit":"Enviar",
"Continue":"Continuar",
"Your_Annual_Income":"Ingresos anuales",
"Only_non-positive_amounts_":"S\u00f3lo valores negativos son aceptados en este campo",
"An_exception_has_been_fire":"An exception has been fired executing the operation ",
"We_will_need_financial_information_from_you_in_order_to_process_your_credit_card_request":"Necesitamos que nos proporcione informaci\u00f3n financiera para poder realizar su petici\u00f3n.",
"Number":"N\u00famero",
"SESSION_ACCESS_FAILURE":"Sesi\u00f3n no disponible. Establezca sesi\u00f3n de nuevo",
"Amount":"Saldo",
"_to_an_object.Error_":"to an object.Error\: ",
"The_source_account_and_the":"Las cuentas origen y destino no pueden coincidir",
"City":"Ciudad",
"You_have_been_approved_for_a_brand_new":"Se ha aprobado la asignaci\u00f3n de su nueva tarjeta",
"Input_mandatory_data":"Llenar campos obligatorios",
"Select_an_account_FROM_which_to_make_the_payment":"Seleccione la cuenta origen del pago\:",
"Social_Security":"N\u00famero de seguridad social",
"Object_":"Object  ",
"You_entered_your_income_wi":"El importe correspondiente a sus ingresos no es num\u00e9rico. ",
"Demo_Bank_-_Apply_for_a_credit_card":"Demo Bank - Adquisici\u00f3n de tarjeta de cr\u00e9dito",
"No":"No",
"doesnt_have_an_attribute_n":"doesnt have an attribute named \'operationName\', the operation to fire has not been defined ",
"You_must_specify_your_soci":"Debe proporcionar su n\u00famero de seguridad social. ",
"OK":"Bien",
"SIGNON_USER_NOT_FOUND":"Usuario no encontrado en la base de datos",
"First_Name":"Nombre",
"You_have_to_fill_out_an_ac":"Debe introducir un n\u00famero de cuenta. ",
"Savings_Account":"Cuenta de ahorros",
"Close":"Cerrar",
"Reset_Fin_Info":"Reiniciar proceso &quot;Informaci\u00f3n Financiera&quot;",
"Cancel_Application":"Cancelar la aplicaci\u00f3n",
"Sign_In":"Entrar",
"Zip_Code":"C\u00f3digo postal",
"Input_is_required_in_this_":"Input is required in this field ",
"Continue_on_with_application":"Continuar con la petici\u00f3n",
"The_String___":"The String \" ",
"I_have_an_account":"Tengo una cuenta en su banco con el siguiente n\u00famero\:",
"Only_zero_amounts_are_allo":"S\u00f3lo valores cero son aceptados en este campo",
"User_ID":"Usuario\:",
"Payment_was_successfully_completed":"Pago realizado satisfactoriamente.",
"SIGNON_NO_PASSWORD":"Clave de acceso no disponible para entrar en el sistema",
"Initialization_OK":"Initialization OK",
"Transfer_was_successfully_completed":"Transferencia realizada satisfactoriamente.",
"Upon_approval_you_will_receive_your_new_card_within_two_weeks":"Una vez aprobado, usted recibir\u00e1 su tarjeta en dos semanas",
"Invalid_argument":"Invalid argument ",
"Payments":"Pagos",
"Transfers":"Transferencias",
"Logoff":"Desconexi\u00f3n",
"Thanks_message":"Gracias por confiar en los servicios de &quot;Demo Bank&quot;.",
"The_cards":"Tarjetas",
"_-s_<server_address\>_Serve":"-s <server_address\>\tServer address. ",
"Amount_validation_error":"Error en la validaci\u00f3n de la cantidad suministrada",
"Initialitation_OK":"Initialitation OK ",
"Apt_Suite":"N\u00famero de piso",
"Amount_class_required":"El tipo debe ser Amount",
"error_":"error\: ",
"Exception_processing_reque":"Exception processing request\: ",
"Welcome_to_Demo_Bank":"Bienvenido a Demo Bank",
"I_do_not_have_an_account":"No tengo ninguna cuenta en su banco, pero quiero adquirir una de sus tarjetas de cr\u00e9dito",
"_-h__________________This_":"-h                  This message.",
"Cannot_convert_the_operati":"Cannot convert the operation  ",
"Please_Sign-In":"Por favor, identif\u00edquese para acceder al sistema",
"Please_Try_Again":"Por favor, int\u00e9ntelo de nuevo\!",
"Validation_failed_since_va":"Validation failed since value is null. ",
"___MUST_be_exactly_":"\" MUST be exactly  ",
"State":"Estado",
"Account_Name":"Nombre de cuenta",
"Select_an_account_TO_which_a_payment_is_to_be_made":"Seleccione la cuenta destino del pago\:",
"Select_an_account_FROM_which_money_is_dispensed":"Seleccione la cuenta origen de la transferencia\:",
"ERROR_in_Server___":"ERROR in Server \:  ",
"Missing/Incorrect_Information":"Informaci\u00f3n insuficiente o incorrecta",
"You_must_specify_your_inco":"Debe proporcionar sus ingresos. ",
"The_Universal_Card":"La tarjeta Universal",
"Are_you_sure":"\u00bfEst\u00e1 usted seguro(a) de cancelar su petici\u00f3n?",
"Demo_Bank_Congratulations":"Demo Bank - Enhorabuena",
"The_Action":"The Action ",
"Length_of_Employment":"Antig\u00fcedad",
"The_field_simulateError_is":"El campo simulateError est\u00e1 puesto a true en la definici\u00f3n de los datos de la operaci\u00f3n SaveFinancialInfoOperation",
"Cannot_provide_service_now":"Fuera de servicio temporalmente",
"Wellcome_message":"Enhorabuena por decidirse por una de nuestras tarjetas de cr\u00e9dito. Por favor indique si ya tiene cuenta en nuestro banco, proporcionando el n\u00famero de cuenta correspondiente. En caso contrario, le invitaremos a que nos proporcione informaci\u00f3n para la adquisici\u00f3n de su tarjeta. Seleccione la opci\u00f3n correspondiente y pulse Continuar.",
"UserId_not_found_in_input_":"UserId not found in input context data 127.0.0.1_80 \= 127.0.0.1\:80",
"for":"de",
"Select_Language":"Seleccione el idioma\:",
"Validation_failed_since_th":"Validation failed since the String ",
"errorCode_not_found_in_con":"errorCode not found in context\:  ",
"_should_be_an_instance_of_":"deber\u00eda ser una instancia num\u00e9rica",
"Income_not_available":"El campo &quot;Ingresos&quot; no est\u00e1 disponible. Probablemente, el par\u00e1metro &quot;dse_ignoreValidationResults&quot; est\u00e1 puesto a &quot;true&quot; en la definici\u00f3n del proceso",
"We_apologize":"Sentimos no poder servir su petici\u00f3n debido a los siguientes motivos\:",
"SIGNON_NO_USERID":"Usuario no disponible para entrar en el sistema",
"You_have_to_give_us_your_n":"Debe proporcionar su nombre. ",
"months":"meses",
"UserID_is_not_valid._Try_a":"UserID is not valid. Pruebe de nuevo con \"user01\" o con \"user02\" ",
"Cards_text":"El conjunto de tarjetas de cr\u00e9dito de Demo Bank proporciona caracter\u00edsticas adecuadas a su inter\u00e9s. Cada tarjeta dispone de beneficios \u00fanicos. Pulse en cada una de ellas para obtener informaci\u00f3n detallada.",
"years":"a\u00f1os",
"SIGNON_INVALID_PASSWORD":"Clave de acceso inv\u00e1lida",
"Invalid_mapping_of_the_Err":"Invalid mapping of the Error_Messages field ",
"I_choose_not_to_apply_at_this_time":"No realizar la petici\u00f3n de momento",
"Demo_Bank_credit_card":"de Demo Bank. Enhorabuena\! Su petici\u00f3n ser\u00e1 enviada a nuestro centro de proceso con m\u00e1xima prioridad. Si prefiere cursar su petici\u00f3n en otro momento, cancele la transacci\u00f3n. En caso contrario, seleccione &quot;Proceder con mi elecci\u00f3n&quot;, pulse Continuar y disfrute de las ventajas de su nueva tarjeta\!.",
"Credit_Card":"Tarjeta de Cr\u00e9dito",
"Password":"Clave de acceso\:",
"Loan_Payment":"Pago de pr\u00e9stamo",
"Only_positive_amounts_are_":"S\u00f3lo valores positivos mayores de cero son aceptados en este campo",
"Continue_processing_application_with_my_credit_card_selection":"Continuar de acuerdo con la tarjeta seleccionada",
"The_Classic_Card":"La tarjeta Classic",
"Process_was_successfully_reset":"El proceso se ha reiniciado satisfactoriamente. Los cambios realizados en la definici\u00f3n del proceso ya est\u00e1n disponibles.",
"You_havent_indicated_wheth":"No ha indicado si tiene una cuenta en nuestro banco o si desea en cualquier caso obtener una de nuestras tarjetas de cr\u00e9dito.",
"Last_Name":"Apellido",
"Confirmation_Page":"Confirmaci\u00f3n",
"Congratulations":"Enhorabuena\!",
"Amount_paid":"Cantidad pagada\:",
"Do_you_have_a":"Tiene una",
"_-p_<dseIniPath\>__Path_to_":"-p <dseIniPath\>\t\tPath to the server configuration file. ",
"Here_we_obtain_the_user_in":"Here we obtain the user information ",
"Clear":"Borrar",
"Final_message":"de Demo Bank\! Enhorabuena por su elecci\u00f3n. Usted recibir\u00e1 su tarjeta en el plazo de dos semanas, juntamente con informaci\u00f3n relacionada con sus derechos y privilegios por disponer de una de las tarjetas de Demo Bank. No dude en ponerse en contacto con nuestro centro de atenci\u00f3n al cliente para cualquier otro menester.",
"Cancel":"Cancelar",
"Employer_Name":"Empresa en la que trabaja",
"Select_Flavor":"Seleccione sabor\:",
"Reset_Credit_Card_Proc":"Reiniciar proceso &quot;Tarjeta de Cr\u00e9dito&quot;",
"_characters_long":"characters long ",
"Other_Household_Income":"Otros ingresos",
"Unable_to_unchain_the_acti":"Unable to unchain the action context, this might cause further execution problems.Action\: ",
"Select_Operation":"Seleccione la operaci\u00f3n\:",
"Connecting_with_the_server":"Connecting with the server...",
"___MUST_be_at_most_":"\" MUST be at most  "})
