package com.ibm.btt.application.op.x073;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/07/16 18:13:29
 */
public class X073_test_Flow_op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Context context=this.getContext();
	  for (int i = 0; i < 10; i++) {
		  context.setValueAt("TestMutiWidgetList."+i+".Field1", "field"+i);
		  context.setValueAt("TestMutiWidgetList."+i+".Field2", "account"+i);
		  context.setValueAt("TestMutiWidgetList."+i+".Field3", "data"+i);
		  context.setValueAt("TestMutiWidgetList."+i+".flag", i);
		  int j=i%4;
		  if(j==0){
			  context.setValueAt("TestMutiWidgetList."+i+".Image", "img/10days.jpg");
		  }else if(j==1){
			  context.setValueAt("TestMutiWidgetList."+i+".Image", "img/15days.jpg");
			  
		  }else if(j==2){
			  context.setValueAt("TestMutiWidgetList."+i+".Image", "img/7days.jpg");
			  
		  }else{
			  context.setValueAt("TestMutiWidgetList."+i+".Image", "");
			  
		  }
	}
	  fireExitEvent("opEvt");
  }
}
