({
"_1ECA_NLS_Page":"Fran\u00e7aise\:\u00c9v\u00e9nements, conditions, actions et page NLS",
"_1Simple_Table_NLS_Page":"Fran\u00e7aise\:Simple Formulaire NLS Page",
"_0Contents":"R\u00e9pertoire",
"_0Reset_Button":"Reset",
"_1Simple_NLS_Page":"Fran\u00e7aise\:Simple NLS Page",
"_2Text_Value2":"Bonjour, l\'oc\u00e9an\!",
"_2Text_Value1":"Bonjour, cowboy\!",
"_2Tip_Message2":"Bonjour, fleurs\!",
"_2Tip_Message1":"Bonjour, UFO\!",
"_0First_Page_Button":"Accueil",
"_0Submit_Button":"Soumis",
"_0Button_Button":"Button",
"_1Complex_NLS_Page":"Fran\u00e7aise\:Complexe NLS Page",
"_Message_Dijit_PlaceHolder_Msg":"Bonjour, {0}",
"_Table_Column5":"Colonne5(Commune)",
"_Table_Column4":"Colonne4(String)",
"_Table_Column3":"Colonne3(Number)",
"_SelectList_Option_4":"Alternatives 5",
"_1Negative_NLS_Page":"Fran\u00e7aise\:NLS page non-normale test de logique",
"_Table_Column2":"Colonne2(Date)",
"_SelectList_Option_3":"Alternatives 4",
"_Table_Column1":"Colonne1(Monnaie)",
"_SelectList_Option_2":"Alternatives 3",
"_SelectList_Option_1":"Alternatives 2",
"_SelectList_Option_0":"Alternatives 1"})
