package com.ibm.btt.test.util;
import java.util.Random;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.test.util.DateUtilForTest;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/09/12 00:15:00
 */
public class InitOtherSettledInfoOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
	
	Random ran = new Random();
  public void execute() throws Exception {
	  KeyedCollection k = getContext().getKeyedCollection();
	  k.setValueAt("SettledBillList01.0.BillDate", DateUtilForTest.getDate());
	  k.setValueAt("SettledBillList01.0.PaymentDueDate",DateUtilForTest.getDate());
	  double billNeedPay = ran.nextDouble()*1000;
	  k.setValueAt("SettledBillList01.0.CurBillNeedPay", billNeedPay);
	  k.setValueAt("SettledBillList01.0.MinBill",billNeedPay);
	  k.setValueAt("SettledBillList02.0.LastBillBalance",1000.00);
	  k.setValueAt("SettledBillList02.0.CurBillAlreadyPay",13900.00);
	  k.setValueAt("SettledBillList02.0.NewAddBill",5000.00);
	  k.setValueAt("SettledBillList02.0.Withdrawl",50.00);
	  k.setValueAt("SettledBillList02.0.Interest",100.00);
	  k.setValueAt("SettledBillList02.0.CurBillBalance",1000.00);
	  
	  fireExitEvent("opEvt");
  }
}
