package com.ibm.btt.test.util;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;

/**
 * Class Generated by BTT Tool Created since: 2013/09/12 11:14:49
 */
public class InitLoanAcctInfo extends BTTServerOperation {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {
		KeyedCollection k = getContext().getKeyedCollection();
		IndexedCollection loanAcctList = (IndexedCollection) k
				.getElementAt("LoanAcctList");
		loanAcctList.removeAll();
		KeyedCollection loanAcct0 = new KeyedCollection();
		loanAcct0.setDynamic(true);
		loanAcct0.setName("loanAcct");
		loanAcct0.setValueAt("LoanAcctNo", "6228 1399 1233 4221 1001 **** 88");
		loanAcct0.setValueAt("SignStatus", "Signed ");
		loanAcct0.setValueAt("AcctStatus", "Normal");
		loanAcct0.setValueAt("LoanType", "Individual Consumer Loan");
		loanAcct0.setValueAt("LoanAmount", 1000.00);
		loanAcct0.setValueAt("AvailableAmout", 0.00);
		loanAcctList.addElement(loanAcct0);

		KeyedCollection loanAcct1 = new KeyedCollection();
		loanAcct1.setDynamic(true);
		loanAcct1.setName("loanAcct");
		loanAcct1.setValueAt("LoanAcctNo", "6228 1255 1390 4221 0066 **** 59");
		loanAcct1.setValueAt("SignStatus", "Signed ");
		loanAcct1.setValueAt("AcctStatus", "Normal");
		loanAcct1.setValueAt("LoanType", "Individual Auto Loan");
		loanAcct1.setValueAt("LoanAmount", 2120.00);
		loanAcct1.setValueAt("AvailableAmout", 10.00);
		loanAcctList.addElement(loanAcct1);

		KeyedCollection loanAcct2 = new KeyedCollection();
		loanAcct2.setDynamic(true);
		loanAcct2.setName("loanAcct");
		loanAcct2.setValueAt("LoanAcctNo", "4332 3600 2388 4221 0306 **** 63");
		loanAcct2.setValueAt("SignStatus", "Signed ");
		loanAcct2.setValueAt("AcctStatus", "Normal");
		loanAcct2.setValueAt("LoanType", "Individual Housing Loan");
		loanAcct2.setValueAt("LoanAmount", 2843.00);
		loanAcct2.setValueAt("AvailableAmout", 100.00);
		loanAcctList.addElement(loanAcct2);

		KeyedCollection payeeAcct = (KeyedCollection)k.getElementAt("PayeeAcct");
		payeeAcct.setValueAt("PayeeName", "Mr Yang");
		
		IndexedCollection payeeAcctList = (IndexedCollection) k
				.getElementAt("PayeeAcctList");
		payeeAcctList.removeAll();
		KeyedCollection payeeAcct0 = new KeyedCollection();
		payeeAcct0.setDynamic(true);
		payeeAcct0.setName("payeeAcct");
		payeeAcct0.setValueAt("PayeeAcctNo", 0);
		payeeAcct0.setValueAt("PayeeName", "Mr Yang");
		payeeAcct0.setValueAt("PayeeBank", "Test");
		payeeAcct0.setValueAt("DrawnAmount", 0.00);
		payeeAcct0.setValueAt("CapitalAmount", "");
		payeeAcctList.addElement(payeeAcct0);
			
		KeyedCollection payeeAcct1 = new KeyedCollection();
		payeeAcct1.setDynamic(true);
		payeeAcct1.setName("payeeAcct");
		payeeAcct1.setValueAt("PayeeAcctNo", 1);
		payeeAcct1.setValueAt("PayeeName", "Miss Zhang");
		payeeAcct1.setValueAt("PayeeBank", "Bank Of China, ShangHai Branch");
		payeeAcct1.setValueAt("DrawnAmount", 0.00);
		payeeAcct1.setValueAt("CapitalAmount", "");
		payeeAcctList.addElement(payeeAcct1);
		
		KeyedCollection payeeAcct2 = new KeyedCollection();
		payeeAcct2.setDynamic(true);
		payeeAcct2.setName("payeeAcct");
		payeeAcct2.setValueAt("PayeeAcctNo", 2);
		payeeAcct2.setValueAt("PayeeName", "Mr Li");
		payeeAcct2.setValueAt("PayeeBank", "Bank Of China, QingDao Branch");
		payeeAcct2.setValueAt("DrawnAmount", 0.00);
		payeeAcct2.setValueAt("CapitalAmount", "");
		payeeAcctList.addElement(payeeAcct2);
		
		KeyedCollection payeeAcct3 = new KeyedCollection();
		payeeAcct3.setDynamic(true);
		payeeAcct3.setName("payeeAcct");
		payeeAcct3.setValueAt("PayeeAcctNo", 3);
		payeeAcct3.setValueAt("PayeeName", "Miss Ye");
		payeeAcct3.setValueAt("PayeeBank", "China Merchants Bank, Guangzhou Branch");
		payeeAcct3.setValueAt("DrawnAmount", 0.00);
		payeeAcct3.setValueAt("CapitalAmount", "");
		payeeAcctList.addElement(payeeAcct3);
		
		fireExitEvent("opEvt");
	}
}
