({
"Reset_Process":"Reset Process",
"ERROR_in_Server__":"ERROR in Server\: ",
"Only_non-negative_amounts_":"Only non-negative amounts are allowed in this field ",
"The_-from_account-_and_-to":"The -from account- and -to account- entries must not reference the same account. ",
"Payment":"Payment",
"All_amount_values_are_allo":"All amount values are allowed in this field ",
"Account_Transfer":"Account Transfer",
"You_may_go_back":"You may go back and correct the application. If you have any question, please call <B\>99-9-999-999-9999</B\> and we will be happy to help you to take your application.",
"Cannot_provide_service":"Cannot provide service",
"Only_non-zero_amounts_are_":"Only non-zero amounts are allowed in this field ",
"Cancel_credit_card_application":"Cancel credit card application",
"The_Platinum_Card":"The Platinum Card",
"Operation_warning":"Operation warning\:",
"We_apologize_II":"We apologize, but we are unable to process your application request at this time. Please, try again later or resume your application by selecting any other service request. The following information messages have been gotten from the infrastructure system\:",
"Only_negative_amounts_are_":"Only negative amounts are allowed in this field ",
"Please_enter_the_amount_of_the_payment":"Please enter the amount of the payment",
"Use__java_com.ibm.btt.samp":"Use\: java com.ibm.btt.samples.appl.StartServerServlet [-s <server_address\>] [-p <dseIniPath\>] [-h]",
"You_have_selected_to_apply_for_a":"You have selected to apply for a",
"Occupation":"Occupation",
"Date_of_Birth":"Date of birth",
"Exception_in_main_":"Exception in main\:",
"Try_again":"You may try again by selecting your choice in the menu. If you have any question, please call <B\>99-9-999-999-9999</B\> and we will be happy to help you to take your application.",
"Please_enter_the_amount_of_money_to_be_transferred":"Please enter the amount of money to be transferred",
"Cross_validation_errors_have_occurred":"Cross validation errors have occurred\:",
"Process_my_selection":"Process my selection",
"Yes":"Yes",
"___MUST_be_at_least_":"\" MUST be at least  ",
"Cancel_Confirmation":"Cancel Confirmation",
"Account_Summary":"Account Summary",
"String_validation_error":"String validation error ",
"Amount_transferred":"Amount transferred",
"Are_you_a_US_citizen_or_a_permanent_US_resident":"Are you a US citizen or a permanent US resident?",
"Social_security_numbers_mu":"Social security numbers must not contain non-numeric characters. ",
"Type":"Type",
"Ignored_field_val_for_income":"Ignored field validation results for Income\:",
"Home_Address":"Home Address",
"_cannot_be_converted_to_an":"cannot be converted to an Object of Type  ",
"Checking_Account":"Checking Account",
"Select_an_account_TO_which_money_is_deposited":"Select an account TO which money is deposited",
"No_amount_values_are_allow":"No amount values are allowed in this field ",
"Middle_Name":"Middle Name",
"Submit":"Submit",
"Continue":"Continue",
"Your_Annual_Income":"Your Annual Income",
"Only_non-positive_amounts_":"Only non-positive amounts are allowed in this field ",
"An_exception_has_been_fire":"An exception has been fired executing the operation ",
"We_will_need_financial_information_from_you_in_order_to_process_your_credit_card_request":"We will need financial information from you in order to process your credit card request.",
"Number":"Number",
"SESSION_ACCESS_FAILURE":"Session Access Failure. Please establish session.",
"Amount":"Amount",
"_to_an_object.Error_":"to an object.Error\: ",
"The_source_account_and_the":"The source account and the target account MUST not be the same. ",
"City":"City",
"You_have_been_approved_for_a_brand_new":"You have been approved for a brand new",
"Input_mandatory_data":"Input mandatory data",
"Select_an_account_FROM_which_to_make_the_payment":"Select an account FROM which to make the payment\:",
"Social_Security":"Social security number",
"Object_":"Object  ",
"You_entered_your_income_wi":"You entered your income with non-numeric characters. ",
"Demo_Bank_-_Apply_for_a_credit_card":"Demo Bank - Apply for a credit card",
"No":"No",
"doesnt_have_an_attribute_n":"doesnt have an attribute named \'operationName\', the operation to fire has not been defined ",
"You_must_specify_your_soci":"You must specify your social security number for this application to be processed. ",
"OK":"OK",
"SIGNON_USER_NOT_FOUND":"Provided userid not found in the database",
"First_Name":"First Name",
"You_have_to_fill_out_an_ac":"You have to fill out an account number. ",
"Savings_Account":"Savings Account",
"Close":"Close",
"Reset_Fin_Info":"Reset &quot;Financial Information&quot; process",
"Cancel_Application":"Cancel Application",
"Sign_In":"Sign-In",
"Zip_Code":"Zip code",
"Input_is_required_in_this_":"Input is required in this field ",
"Continue_on_with_application":"Continue on with application",
"The_String___":"The String \" ",
"I_have_an_account":"I have an account with your bank, my account number is\:",
"Only_zero_amounts_are_allo":"Only zero amounts are allowed in this field ",
"User_ID":"User ID\:",
"Payment_was_successfully_completed":"Payment was successfully completed.",
"SIGNON_NO_PASSWORD":"Password not available to perform the sign-on",
"Initialization_OK":"Initialization OK",
"Transfer_was_successfully_completed":"Transfer was successfully completed.",
"Upon_approval_you_will_receive_your_new_card_within_two_weeks":"Upon approval you will receive your new card within two weeks",
"Invalid_argument":"Invalid argument ",
"Payments":"Payments",
"Transfers":"Transfers",
"Logoff":"Logoff",
"Thanks_message":"Thank you very much for using &quot;Demo Bank&quot; services. ",
"The_cards":"The cards",
"_-s_<server_address\>_Serve":"-s <server_address\>\tServer address. ",
"Amount_validation_error":"Amount validation error ",
"Initialitation_OK":"Initialitation OK ",
"Apt_Suite":"Apt. or Suite number",
"Amount_class_required":"Amount class required ",
"error_":"error\: ",
"Exception_processing_reque":"Exception processing request\: ",
"Welcome_to_Demo_Bank":"Welcome to Demo Bank",
"I_do_not_have_an_account":"I do not have an account with your bank, but would like to apply for your credit card.",
"_-h__________________This_":"-h                  This message.",
"Cannot_convert_the_operati":"Cannot convert the operation  ",
"Please_Sign-In":"Please Sign-In",
"Please_Try_Again":"Please Try Again\!",
"Validation_failed_since_va":"Validation failed since value is null. ",
"___MUST_be_exactly_":"\" MUST be exactly  ",
"State":"State",
"Account_Name":"Account Name",
"Select_an_account_TO_which_a_payment_is_to_be_made":"Select an account TO which a payment is to be made\:",
"Select_an_account_FROM_which_money_is_dispensed":"Select an account FROM which money is dispensed",
"ERROR_in_Server___":"ERROR in Server \:  ",
"Missing/Incorrect_Information":"Missing/Incorrect Information",
"You_must_specify_your_inco":"You must specify your income for this application to be processed. ",
"The_Universal_Card":"The Universal Card",
"Are_you_sure":"Are you sure to cancel your request?",
"Demo_Bank_Congratulations":"Demo Bank - Congratulations",
"The_Action":"The Action ",
"Length_of_Employment":"Length of Employment",
"The_field_simulateError_is":"The field simulateError is set to true in the SaveFinancialInfoOperation data ",
"Cannot_provide_service_now":"Cannot provide service now",
"Wellcome_message":"Congratulations on your first steps towards applying for a Demo Bank Credit Card\! If you have an account with us then please select the appropriate option below, and fill in your account number. Otherwise, we will gather information from you to assist in the credit card application process. If you have an account with us you might be approved right away\! To begin the credit card application process, please select the appropriate option below, and click Continue.",
"UserId_not_found_in_input_":"UserId not found in input context data 127.0.0.1_80 \= 127.0.0.1\:80",
"for":"for",
"Select_Language":"Select Language\:",
"Validation_failed_since_th":"Validation failed since the String ",
"errorCode_not_found_in_con":"errorCode not found in context\:  ",
"_should_be_an_instance_of_":"should be an instance of an amount ",
"Income_not_available":"&quot;Income&quot; field is not available. Probably, parameter &quot;dse_ignoreValidationResults&quot; is set &quot;true&quot; in the process definition",
"We_apologize":"We apologize, but we are unable to process your application for the following reasons\:",
"SIGNON_NO_USERID":"Userid not available to perform the sign-on",
"You_have_to_give_us_your_n":"You have to give us your name for this application to be processed. ",
"months":"months",
"UserID_is_not_valid._Try_a":"UserID is not valid. Try again with \"user01\" or \"user02\" ",
"Cards_text":"The Demo Bank family of credit cards has something for every need and every interest. Each card has a unique mix of features and benefits. Click on a card below for more information on it.",
"years":"years",
"SIGNON_INVALID_PASSWORD":"Invalid password",
"Invalid_mapping_of_the_Err":"Invalid mapping of the Error_Messages field ",
"I_choose_not_to_apply_at_this_time":"I choose not to apply at this time",
"Demo_Bank_credit_card":"Demo Bank credit card. Congratulations\! Your application will now be sent to our customer center for immediate processing. If you would like to apply instead at another time, please select to cancel the transaction. Otherwise, select continue and take a step towards greater control of your finances\!",
"Credit_Card":"Credit Card",
"Password":"Password\:",
"Loan_Payment":"Loan Payment",
"Only_positive_amounts_are_":"Only positive amounts are allowed in this field ",
"Continue_processing_application_with_my_credit_card_selection":"Continue processing application with my credit card selection",
"The_Classic_Card":"The Classic Card",
"Process_was_successfully_reset":"Process was successfully reset. New updates on the process definition are already in place.",
"You_havent_indicated_wheth":"You havent indicated whether you have an account with us, or if you do not but would like to apply for our credit card. ",
"Last_Name":"Last Name",
"Confirmation_Page":"Confirmation Page",
"Congratulations":"Congratulations\!",
"Amount_paid":"Amount paid\:",
"Do_you_have_a":"Do you have a",
"_-p_<dseIniPath\>__Path_to_":"-p <dseIniPath\>\t\tPath to the server configuration file. ",
"Here_we_obtain_the_user_in":"Here we obtain the user information ",
"Clear":"Clear",
"Final_message":"Demo Bank card\! Congratulations on your choice. You will be receiving your card in the mail within the next two weeks. With your card you will also receive our brochure listing your rights and priviledges as a Demo Bank cardholder. Please don\'t hesitate to contact our customer care centers for any issues or questions you may have.",
"Cancel":"Cancel",
"Employer_Name":"Employer Name",
"Select_Flavor":"Select Flavor\:",
"Reset_Credit_Card_Proc":"Reset &quot;Credit Card&quot; process",
"_characters_long":"characters long ",
"Other_Household_Income":"Other Household Income",
"Unable_to_unchain_the_acti":"Unable to unchain the action context, this might cause further execution problems.Action\: ",
"Select_Operation":"Select Operation\:",
"Connecting_with_the_server":"Connecting with the server...",
"___MUST_be_at_most_":"\" MUST be at most  "})
