package com.ibm.btt.application.op;

import java.math.BigDecimal;

import com.ibm.btt.annotation.EVENT;
import com.ibm.btt.automaton.ext.DSEOperationState;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.OperationRepliedEvent;
import com.ibm.btt.base.types.impl.Currency;

/**
 * Class Generated by BTT Tool Created since: 2012/09/10 15:23:06
 */
public class myOp extends BTTServerOperation {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	@EVENT({ "ok", "other" })
	public void execute() throws Exception {

		System.out.println("myOp + execute");
		this.setValueAt("typeData.currencyData", new Currency("USD",
				new BigDecimal(1000)));

		KeyedCollection opData = this.getContext().getKeyedCollection();
		this.setValueAt("beanData.myBean.username", "Jing Li Chong");
		this.setValueAt("beanData.myBean.password", "0123456");
		KeyedCollection tableData = (KeyedCollection) opData
				.getElementAt("tableData");
		IndexedCollection myTable = (IndexedCollection) tableData
				.getElementAt("myTable");

		for (int i = 0; i < myTable.size(); i++) {
			myTable.setValueAt(i + ".name", "Helen" + i);
			myTable.setValueAt(i + ".position", "Tester");
			myTable.setValueAt(i + ".age", "24");

		}
		OperationRepliedEvent event = new OperationRepliedEvent(this);
		com.ibm.btt.base.Hashtable ht = new com.ibm.btt.base.Hashtable();
		ht.put(DSEOperationState.EXIT_EVENT_NAME, "ok");
		event.setParameters(ht);
		fireHandleOperationRepliedEvent(event);

		System.out.println(this.getContext().getKeyedCollection());
	}
}
