package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/10/17 14:08:32
 */
public class TestOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  System.out.println("ss");
  }
}
