package com.ibm.btt.application.op;
import com.ibm.btt.automaton.ext.DSEOperationState;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.OperationRepliedEvent;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/09/10 17:25:02
 */
public class yourOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
		OperationRepliedEvent event = new OperationRepliedEvent(this);
		com.ibm.btt.base.Hashtable ht = new com.ibm.btt.base.Hashtable();
		ht.put(DSEOperationState.EXIT_EVENT_NAME, "go");
		event.setParameters(ht);
		fireHandleOperationRepliedEvent(event);
		
		System.out.println(this.getContext().getKeyedCollection()+"======================");
  }
}
