package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/03/05 09:38:21
 */
public class createData19_21 extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection k = this.getContext().getKeyedCollection();
		IndexedCollection tableList = (IndexedCollection) k.getElementAt("usernameList");
		for (int i = 0; i < tableList.size() ; i++) {
			tableList.setValueAt(i + ".username", "username"+i);
		
		}
		fireExitEvent("creadata");
		  

  }
}
