package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/01/24 16:41:52
 */
public class CreateDataForWidget extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Context context = getContext();
	  
	  context.setValueAt("TestString", "This is a string data");
	  //for image
	  context.setValueAt("TestImage", "img/10days.jpg");
	  //for rich text data
	  context.setValueAt("RichTextEditorData", "This is a rich text sample.");
	  //Sex. 1 is male ,0 is female
	  context.setValueAt("SexData",1);
	  //for CheckBox
	  context.setValueAt("CheckBoxData",true);
	  
	  //for text
	  context.setValueAt("TextData",888);
	  //for isMandatory=true
	  //context.setValueAt("TextData2","I got a boy");
	  //for read only
	  context.setValueAt("TestDataForReadOnly","Dual Life");
	  //for password
	  context.setValueAt("PasswordData","Dancing Queen");
	  //for hidden field 
	  context.setValueAt("StringForHiddenField","This is hidden value -- dataname");
	  
	  //for select list
	  for (int i = 0; i < 3; i++) {
		  context.setValueAt("Select_List."+i+".CityName", "City"+i);
		  context.setValueAt("Select_List."+i+".CityValue", i);
		  context.setValueAt("Combo_List."+i+".CountryName", "Country"+i);
		  
	 }
	  
	  
	  fireExitEvent("opEvt");
  }
}
