package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/05/08 17:02:34
 */
public class G001_initDataOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	 KeyedCollection k = this.getContext().getKeyedCollection();
	IndexedCollection historyList = (IndexedCollection) k.getElementAt("transferHistory");
	historyList.removeAll();
	IndexedCollection allHistory = TransferHistoryDB.getInstance().getAllHistory();
//	Double tt = 0D;
	for (int i = 0; i < 10; i++){
		KeyedCollection history = (KeyedCollection) allHistory.getElementAt(i + "");
		history.setValueAt("status","successfully transferred");
	
//		try{			
//			Currency cy =  (Currency)history.getValueAt("amount");
//			tt +=cy.getValue().doubleValue();
//		}catch(Exception e){}
//		
		historyList.addElement(history);
//		history.getElementAt("transfer_date");
	}
//	KeyedCollection history = (KeyedCollection) allHistory.getElementAt(9);
//	history.setValueAt("toAccount", "total");
//	history.setValueAt("amount", new Currency("EUR", new BigDecimal(tt)));
//	historyList.addElement(history);
//	
	fireExitEvent("opEvt");
  }
}
