package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Hashtable;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.OperationRepliedEvent;
import com.ibm.btt.dojo.model.TreeModel;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/05/27 14:37:08
 */
public class G021_initDataOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection kc=this.getKeyedCollection();
	  kc.setValueAt("balance", "9999.00");
	  kc.setValueAt("bankCode", "ABC_001");

	  
	  kc.setValueAt("accountList.0.number", "310012342391827364501");
	  kc.setValueAt("accountList.0.description", "Preferred Checking");
	  kc.setValueAt("accountList.0.balance", "234523");
	  
	  kc.setValueAt("accountList.1.number", "960012342391827364501");
	  kc.setValueAt("accountList.1.description", "House Management");
	  kc.setValueAt("accountList.1.balance", "120034");
	  
	  kc.setValueAt("accountList.2.number", "320012342391827364501");
	  kc.setValueAt("accountList.2.description", "Income");
	  kc.setValueAt("accountList.2.balance", "900094");
	  
	  kc.setValueAt("accountList.3.number", "980012342391827364501");
	  kc.setValueAt("accountList.3.description", "Work Management");
	  kc.setValueAt("accountList.3.balance", "879016");
	  
	  //KeyedCollection kc2=(KeyedCollection)this.getKeyedCollection().getValueAt("AllBTTWgtData");
	  
	  kc.setValueAt("AllBTTWgtData.dataForMultiSelect_render.0.name", "Apples");
	  
	  kc.setValueAt("AllBTTWgtData.dataForMultiSelect_render.0.value", "AP");
	  
	  kc.setValueAt("AllBTTWgtData.dataForMultiSelect_render.1.name", "Oranges");
	  kc.setValueAt("AllBTTWgtData.dataForMultiSelect_render.1.value", "OR");
	  
	  kc.setValueAt("AllBTTWgtData.dataForMultiSelect_render.2.name", "Pears");
	  kc.setValueAt("AllBTTWgtData.dataForMultiSelect_render.2.value", "PE");
	  //kc.setValueAt("AllBTTWgtData.dataForMultiSelect_render.2.selected", "true");
	  //kc.setValueAt("AllBTTWgtData.dataForMultiSelect_render.2.disabled", "true");
	  
	  
	  
	  TreeModel root = (TreeModel) getElementAt("AllBTTWgtData.dataForTree");
	  root.setLabel("root");
	  System.out.println(root.getValue());
	  TreeModel level1_1 = new TreeModel("level1-1", "002", "level1-1");
	  TreeModel level2_1 = new TreeModel("level2-1@leaf", "005@leaf", "leaf2-1");
	  TreeModel level3_1 = new TreeModel("level3-1@leaf", "008@leaf", "leaf3-1");
	  level1_1.addChild(level2_1);
	  level1_1.addChild(level3_1);
	  
	  TreeModel level1_2 = new TreeModel("level1-2", "003", "level1-2");
	  TreeModel level2_2 = new TreeModel("level2-2@leaf", "006@leaf", "leaf2-2");
	  TreeModel level3_2 = new TreeModel("level3-2@leaf", "009@leaf", "leaf3-2");
	  level1_2.addChild(level2_2);
	  level1_2.addChild(level3_2);
	  
	  TreeModel level1_3 = new TreeModel("level1-3", "004", "level1-3");
	  TreeModel level2_3 = new TreeModel("level2-3@leaf", "007@leaf", "leaf-3");
	  level1_3.addChild(level2_3);
	  
	  root.addChild(level1_1);
	  root.addChild(level1_2);
	  root.addChild(level1_3);
	  
	  
	  OperationRepliedEvent event = new OperationRepliedEvent(this);
		Hashtable ht = new Hashtable();
		event.setParameters(ht);
		 ht.put(com.ibm.btt.automaton.ext.DSEOperationState.EXIT_EVENT_NAME,"ok");
	 
		fireHandleOperationRepliedEvent(event);

  }
}
