package com.ibm.btt.application.op;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;

/**
 * Class Generated by BTT Tool Created since: 2012/09/18 11:04:01
 */
public class G028_CreatePaginationData extends BTTServerOperation
{
	private int rowsPerPage;
	private int total;
	private int pageNumber;
	private int pageSize;
	private boolean pagination;

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	private Random rand = new Random();
	public void execute() throws Exception
	{

		KeyedCollection opData = this.getContext().getKeyedCollection();
		
		KeyedCollection paginationData = (KeyedCollection)opData.getElementAt("paginationData");

		if (paginationData == null)
			this.pagination = false;
		else
			this.pagination = true;

		if (pagination)
		{
			rowsPerPage = (Integer) paginationData.getValueAt("rowsPerPage");
			pageNumber = (Integer) paginationData.getValueAt("pageNumber");
			total = (Integer) paginationData.getValueAt("totalRowNumber");

			pageSize = total / rowsPerPage;
			if (total % rowsPerPage > 0)
			{
				pageSize++;
			}

			paginationData.setValueAt("pageNumber", pageNumber);

			if (pageNumber <= 1)
			{
				paginationData.setValueAt("enableNext", "true");
				paginationData.setValueAt("enablePrevious", "false");
			}
			else if (pageNumber == pageSize)
			{
				paginationData.setValueAt("enableNext", "false");
				paginationData.setValueAt("enablePrevious", "true");
			}
			else
			{
				paginationData.setValueAt("enableNext", "true");
				paginationData.setValueAt("enablePrevious", "true");
			}
		}
		
		// save changed value
		//AccountListDB.saveAccountList(accountTable, toSavePageNumber);

		// set value		
//		AccountListDB.getAllAccountList(pageNumber, accountTable);
		IndexedCollection accounts = (IndexedCollection) opData.getElementAt("accounts");
		Map<Integer, String> businessNameMap = new HashMap<Integer, String>();
		businessNameMap.put(0, "savings");
		businessNameMap.put(1, "credit");
		businessNameMap.put(2, "mortgage");
		for (int i = 0; i < accounts.size(); i++) {
			accounts.setValueAt(i + ".idx", pageNumber > 1 ? (pageNumber -1) *10 + i : i);
			accounts.setValueAt(i + ".acctNum", "12345678" + (pageNumber > 1 ? (pageNumber -1) *10 + i : "0" + i));
			accounts.setValueAt(i + ".name",
					businessNameMap.get(rand.nextInt(3)));
			accounts.setValueAt(i + ".balance", rand.nextFloat() * 900000);
		}
		fireExitEvent("ok");
	}
}
