package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Hashtable;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.OperationRepliedEvent;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/07/31 16:49:26
 */
public class GridTestFW extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection kc = this.getKeyedCollection(); 
	  
	  kc.setValueAt("GridTestList.0.GridTestData", "218-061234-01-013");
	  kc.setValueAt("GridTestList.1.GridTestData", "318-065684-01-015");
	  kc.setValueAt("GridTestList.2.GridTestData", "118-065914-01-016");
	  kc.setValueAt("GridTestList.3.GridTestData", "218-061004-01-019");
	  
	  kc.setValueAt("SelectTestList.0.SelectTest", "A");
	  kc.setValueAt("SelectTestList.1.SelectTest", "B");
	  kc.setValueAt("SelectTestList.2.SelectTest", "C");
	  kc.setValueAt("SelectTestList.3.SelectTest", "D");
	  
	  OperationRepliedEvent event = new OperationRepliedEvent(this);
	  Hashtable ht = new Hashtable();
	  event.setParameters(ht);
	  ht.put(com.ibm.btt.automaton.ext.DSEOperationState.EXIT_EVENT_NAME,"OK");
	  fireHandleOperationRepliedEvent(event);
  }
}
