package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/04/01 16:12:45
 */
public class IBK_4_11_MutiWidgetNewOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  Context context= this.getContext();
	  System.out.println("singleResult.Field1="+context.getValueAt("singleResult.Field1"));
	  System.out.println("singleResult.Field2="+context.getValueAt("singleResult.Field2"));
	  System.out.println("singleResult.Field3="+context.getValueAt("singleResult.Field3"));
	  System.out.println("testValidation="+context.getValueAt("testValidation"));
	  
	  System.out.println("TestMutiWidgetListResult.0.Field1="+context.getValueAt("TestMutiWidgetListResult.0.Field1"));
	  System.out.println("TestMutiWidgetListResult.0.Field2="+context.getValueAt("TestMutiWidgetListResult.0.Field2"));
	  System.out.println("TestMutiWidgetListResult.0.Field3="+context.getValueAt("TestMutiWidgetListResult.0.Field3"));
	  
  }
}
