package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Hashtable;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.OperationRepliedEvent;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/01/04 16:07:34
 */
public class IBK_TestOperation extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection kc=this.getKeyedCollection();
	  kc.setValueAt("sampleList.0.ID", "9551234567801");
	  kc.setValueAt("sampleList.0.TEXT", "This is line1\rThis is line2\rThis is line3\rThis is line4\nThis is line5\nThis is line6\nThis is line7\nThis is line8");
	  
	  kc.setValueAt("sampleList.1.ID", "4307288419999");
	  kc.setValueAt("sampleList.1.TEXT", "This is line");
	  
	  kc.setValueAt("sampleList.2.ID", "5324000010111");
	  kc.setValueAt("sampleList.2.TEXT", "This is line1 This is line2 This is line3 This is line4 This is line5 This is line6 This is line7 This is line8");
	  
	  kc.setValueAt("doubleData", new Double(1000.12));
	  
	  
	  System.out.println ("##############  TestOperation " +this.getKeyedCollection());
	 
	  OperationRepliedEvent event = new OperationRepliedEvent(this);
		Hashtable ht = new Hashtable();
		event.setParameters(ht);
		 ht.put(com.ibm.btt.automaton.ext.DSEOperationState.EXIT_EVENT_NAME,"ok");
	 
		fireHandleOperationRepliedEvent(event);
  }
}
