package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/01/24 21:59:26
 */
public class IBK_18_GetAccounts extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  // initiate accounts list value
	  IndexedCollection iColl= (IndexedCollection)getElementAt("accounts");
	  
	  iColl.removeAll();

	  KeyedCollection kColl = (KeyedCollection)iColl.createElement(true);
	  kColl.setValueAt("accountId", "001");
	  kColl.setValueAt("balance", "$123.45");
	  kColl.setValueAt("openDate", "2012-12-01");
	  kColl.setValueAt("type", "Deposit");
	  iColl.addElement(kColl);
	  
	  kColl = (KeyedCollection)iColl.createElement(true);
	  kColl.setValueAt("accountId", "002");
	  kColl.setValueAt("balance", "$678.90");
	  kColl.setValueAt("openDate", "2012-12-02");
	  kColl.setValueAt("type", "Deposit");
	  iColl.addElement(kColl);

	  kColl = (KeyedCollection)iColl.createElement(true);
	  kColl.setValueAt("accountId", "003");
	  kColl.setValueAt("balance", "-$135.79");
	  kColl.setValueAt("openDate", "2012-12-03");
	  kColl.setValueAt("type", "Credit Card");
	  iColl.addElement(kColl);
	  
	  kColl = (KeyedCollection)iColl.createElement(true);
	  kColl.setValueAt("accountId", "004");
	  kColl.setValueAt("balance", "$888.88");
	  kColl.setValueAt("openDate", "2012-12-04");
	  kColl.setValueAt("type", "Credit Card");
	  iColl.addElement(kColl);
	  
	  fireExitEvent("ok");
  }
}
