package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.cs.html.HtmlConstants;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/01/25 01:53:43
 */
public class LaunchOperation extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  System.out.println("hello world");
	  setValueAt(HtmlConstants.REPLYPAGE, "finalPage.jsp");
	  fireExitEvent("ok");
  }
}
