package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.cs.html.HtmlConstants;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/03/05 17:03:03
 */
public class MainPageOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  setValueAt(HtmlConstants.REPLYPAGE, "MainPage.jsp");
  }
}
