package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/16 14:29:15
 */
public class RestartTransferOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Context ctx = getContext();
	  KeyedCollection kc = ctx.getKeyedCollection(); 
	  String[] sub = null;
	  kc.setValueAt("AccountPassword", "");
	  kc.setValueAt("TransferPassword", "");
	  kc.setValueAt("tbTransferRecord.TransferAmount", 0);
	  kc.setValueAt("tbTransferRecord.OutputAccount", "");
	  kc.setValueAt("tbTransferRecord.InputAccount", "");
	  kc.setValueAt("tbTransferRecord.InputBankName", "");
	  kc.setValueAt("tbTransferRecord.InputBankCode", "");
	  kc.setValueAt("tbTransferRecord.InputComment", "");
	  kc.setValueAt("tbTransferRecord.OutputComment", "");
	  kc.setValueAt("tbTransferRecord.OutputAccount", "");
	  
	  IndexedCollection ic = (IndexedCollection) kc.getElementAt("Transfer01List");
	  ic.removeAll();
	  
	  fireExitEvent("ok");
  }
}
