package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/07/04 18:42:13
 */
public class Select extends BTTServerOperation {
  public void execute() throws Exception {
	  getContext().getKeyedCollection().setDynamic(true);
	  getContext().setValueAt("SelectList.0.Label","Beijing");
	  getContext().setValueAt("SelectList.1.Label","Paris");
	  getContext().setValueAt("SelectList.2.Label","Longdon");
	  getContext().setValueAt("SelectList.0.Value","China");
	  getContext().setValueAt("SelectList.1.Value","France");
	  getContext().setValueAt("SelectList.2.Value","Britain");
	  fireExitEvent("Mapping");
  }
}
