package com.ibm.btt.application.op;
import java.util.Locale;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Constants;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2012/08/17 02:27:39
 */
public class SetLocaleOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Context ctx = getContext();
	  Context sessionCtx = ctx.getParent();
	  
	  String currentLocale = sessionCtx.getValueAt(Constants.LOCALE).toString();
	  System.out.println("Current locale is :" + currentLocale);
	 
	  sessionCtx.setValueAt(Constants.LOCALE, new Locale("en-US"));
	  fireExitEvent("ok");
  }
}
