package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/02/28 01:21:40
 */
public class TestComboWidgetOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  Context context = getContext();
		for (int i = 0; i < 10; i++) {
			if (i == 1) {
				context.setValueAt("TestComboList." + i + ".FieldForLabel", "");
				context.setValueAt("TestComboList." + i + ".FieldForValue", "value-" + i);
			}else if (i == 3) {
				context.setValueAt("TestComboList." + i + ".FieldForLabel", "valueIs\"\"");
				context.setValueAt("TestComboList." + i + ".FieldForValue", "");
			}else if (i == 7) {
				context.setValueAt("TestComboList." + i + ".FieldForLabel", null);
				context.setValueAt("TestComboList." + i + ".FieldForValue", "value-" + i);
			}else if (i == 9) {
				context.setValueAt("TestComboList." + i + ".FieldForLabel", "valueIsNull");
				context.setValueAt("TestComboList." + i + ".FieldForValue", null);
			}else {
				context.setValueAt("TestComboList." + i + ".FieldForLabel", "sample-" + i);
				context.setValueAt("TestComboList." + i + ".FieldForValue", "value-" + i);
			}
		}
		fireExitEvent("opEvt");

  }
}
