package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.test.sunxl.utils.DateUtil;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/02/25 16:42:50
 */
public class X061_UC1Op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection k = this.getContext().getKeyedCollection();
		IndexedCollection tableList = (IndexedCollection) k.getElementAt("TableList");
		for (int i = 0; i < 10 ; i++) {
			tableList.setValueAt(i + ".Date_slash", DateUtil.getDate());
			tableList.setValueAt(i + ".Calendar_bar", DateUtil.getXGC());
			tableList.setValueAt(i + ".Calendar_slash", DateUtil.getXGC());
		}
		fireExitEvent("opEvt");
  }
}
