package com.ibm.btt.application.op;
import java.util.Date;
import java.util.Random;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/04/10 15:54:47
 */
public class X061_StringOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
	Random rand = new Random();
  public void execute() throws Exception {
	  
	  KeyedCollection k = this.getContext().getKeyedCollection();
		IndexedCollection stringList01 = (IndexedCollection) k
				.getElementAt("X061_StringList_01");
		IndexedCollection stringList02 = (IndexedCollection) k
		.getElementAt("X061_StringList_02");
		for (int i = 0; i < stringList01.size(); i++) {
			stringList01.setValueAt(i + ".longString", "11122\n222222222222222222222222222\nqqqqqqqqqqqqqqqqqqqqqqqq\rqqqqqqqqqqqqbbbbbbbbbbbbbmmmmmmm" + new Date());
			stringList02.setValueAt(i + ".longString", "hello world");
		}
		fireExitEvent("opEvt");
  }
}
