package ibk.r7.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.cs.html.HtmlConstants;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/01/27 23:38:55
 */
public class MultiSelectPageOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {

	  setValueAt("render.0.name", "Apples");
	  setValueAt("render.0.value", "AP");
	  
	  setValueAt("render.1.name", "Oranges");
	  setValueAt("render.1.value", "OR");
	  
	  setValueAt("render.2.name", "Pears");
	  setValueAt("render.2.value", "PE");
	  setValueAt("render.2.selected", "true");
	  setValueAt("render.2.disabled", "true");
	  
	  fireExitEvent("OK");
//	  setValueAt(HtmlConstants.REPLYPAGE, "multiselect.jsp");
  }
}
