package ibk.r7.op;
import com.ibm.btt.base.BTTServerOperation;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/01/29 22:37:48
 */
public class O1Submit extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  System.out.println(this.getContext().getParent().getKeyedCollection());
	  fireExitEvent("OK");
  }
}
