package com.ibm.btt.application.op.X072;
import java.text.SimpleDateFormat;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/07/24 18:19:33
 */
public class X072_UC4Op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection k = getContext().getKeyedCollection();
	  KeyedCollection customer = (KeyedCollection) k.getElementAt("customer");
	  System.out.println("--------------------------------------------"+customer);
	  String cname= (String) customer.getValueAt("name");
	  System.out.println("name = " + cname);
	  System.out.println("birth = " + customer.getValueAt("birth"));
	  System.out.println("children.0.name = " + customer.getValueAt("children.0.name"));
	  System.out.println("children.0.birth = " + customer.getValueAt("children.0.birth"));
	  System.out.println("children.1.name = " + customer.getValueAt("children.1.name"));
	  System.out.println("children.1.birth = " + customer.getValueAt("children.1.birth"));
	  customer.setValueAt("name", "Katie");
	  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	  customer.setValueAt("birth", sdf.parse("1978-07-08"));
	  customer.setValueAt("children.0.name", "Mary");
	  customer.setValueAt("children.0.birth", sdf.parse("2001-11-01"));
	  customer.setValueAt("children.1.name", "Lucy");
	  customer.setValueAt("children.1.birth", sdf.parse("2002-11-02"));
	  
	  System.out.println("--------------------------------------------");
	  System.out.println("this method is executed!");
	  fireExitEvent("opEvt");
  }
}
