package com.ibm.btt.application.op.X072;
import java.text.SimpleDateFormat;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/08/23 16:29:21
 */
public class X072_UC4_02Op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  KeyedCollection k = getContext().getKeyedCollection();
	  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	  k.setValueAt("customer.children.0.name", "Mary Furlow Op");
	  k.setValueAt("customer.children.0.birth", sdf.parse("2011-02-01"));
	  k.setValueAt("customer.children.1.name", "Lucy Furlow Op");
	  k.setValueAt("customer.children.1.birth", sdf.parse("2011-02-02"));
	  
	  System.out.println(k);
  }
}
