package com.ibm.btt.application.op.X072;
import java.util.Date;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/07/24 17:40:38
 */
public class X072_UC3Op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection k = getContext().getKeyedCollection();
	  k.setValueAt("Op_fstr", "hello from op");
	  k.setValueAt("Op_date", new Date());
	  System.out.println("--------------------------------------------");
	  System.out.println("this method is executed!");
  }
}
