package com.ibm.btt.application.op.X072;
import java.text.SimpleDateFormat;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/08/05 13:57:36
 */
public class X072_UC4_01Op extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection k = getContext().getKeyedCollection();
	  KeyedCollection customer = (KeyedCollection) k.getElementAt("customer");
	  customer.setValueAt("name", "Sara Furlow" );
	  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	  customer.setValueAt("birth", sdf.parse("1977-07-07"));
	  customer.setValueAt("children.0.name", "Mary Furlow");
	  customer.setValueAt("children.0.birth", sdf.parse("2000-01-01"));
	  customer.setValueAt("children.1.name", "Lucy Furlow");
	  customer.setValueAt("children.1.birth", sdf.parse("2002-02-02"));
	  fireExitEvent("opEvt");
  }
}
