package com.ibm.btt.application.op.X072;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.test.util.PaginationUtilForTest;
import com.ibm.btt.test.util.TransferHistoryDB;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/07/24 15:11:36
 */
public class X072_UC2_PaginateOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection k = getContext().getKeyedCollection();
	  KeyedCollection paginationData = (KeyedCollection) k.getElementAt("paginationData");
	  IndexedCollection historyList = (IndexedCollection) k.getElementAt("transferHistory");
	  IndexedCollection allHistory = TransferHistoryDB.getInstance().getAllHistory();
	  historyList = PaginationUtilForTest.paginateTheIColl(paginationData, allHistory, historyList);
	  fireExitEvent("opEvt");
  }
}
