({
"GREATER_ZERO_MESSAGE":"Valor de entrada debe mayor que 0\!",
"NOT_NULL_MESSAGE":"valor de entrada no puede estar vac\u00edo\!",
"_1ECA_NLS_Page":"Espa\u00f1oles\: Eventos, condiciones, acciones y la p\u00e1gina de NLS",
"MONEY_SPENT_B100A200":"El dinero gastado debe superior a 100 e inferior a 200.",
"CAN_NOT_CONST_VALID_TRIANGLE":"De entrada de los tres lados del tri\u00e1ngulo no lo es\!",
"_1Simple_Table_NLS_Page":"Espa\u00f1oles\: Simple Forma p\u00e1gina NLS",
"OMG_SPENT_GREAT_WP":"OMG\! El dinero gastado NO debe m\u00e1s de pago semanal\!",
"_0Contents":"Directorio",
"_0Reset_Button":"Restablecer",
"_1Simple_NLS_Page":"Espa\u00f1oles\: Simple p\u00e1gina NLS",
"_2Text_Value2":"Hola, mar\!",
"_2Text_Value1":"Hola, vaquero\!",
"WEEK_PAY_MSG":"Semana de pago debe no menor de 100.",
"_2Tip_Message2":"Hola, las flores\!",
"_2Tip_Message1":"Hola, UFO\!",
"_0First_Page_Button":"Inicio",
"_0Submit_Button":"Enviado",
"_0Button_Button":"Bot\u00f3n",
"_1Complex_NLS_Page":"Espa\u00f1oles\: NLS P\u00e1gina Compleja",
"_Message_Dijit_PlaceHolder_Msg":"Hola, {0}",
"_Table_Column5":"Columna5(Com\u00fan)",
"INPUTS_CAN_NOT_CONST_VALID_TRIANGLE":"Introduzca los tres lados\: {0}, {1} y {2} no constituyen un tri\u00e1ngulo\!",
"_Table_Column4":"Columna4(String)",
"_Table_Column3":"Columna3(Number)",
"_SelectList_Option_4":"Alternativas 5",
"_1Negative_NLS_Page":"Espa\u00f1oles\: NLS l\u00f3gica no-normales p\u00e1gina de prueba",
"_Table_Column2":"Columna2(Fecha)",
"_SelectList_Option_3":"Alternativas 4",
"_Table_Column1":"Columna1(Moneda)",
"_SelectList_Option_2":"Alternativas 3",
"_SelectList_Option_1":"Alternativas 2",
"_SelectList_Option_0":"Alternativas 1"})
