package com.ibm.btt.test;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2013/02/27 16:11:00
 */
public class IBKE2E_GetAccountBalance extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection kc = this.getKeyedCollection();
		
		System.out.println("***************Begin to call IBKE2E_GetAccountBalance **********");
		
		String fromAccount = (String) kc.getValueAt("FromAccount");
		System.out.println("from account is " + fromAccount);
		java.math.BigDecimal balance = new java.math.BigDecimal(0.0);
		if ("111111111".equals(fromAccount))
		{
			balance = new java.math.BigDecimal(11111.1);
		}
		if ("222222222".equals(fromAccount))
		{
			balance = new java.math.BigDecimal(22222.2);
		}
		if ("333333333".equals(fromAccount))
		{
			balance = new java.math.BigDecimal(-33333.3);
		}
		
		kc.setValueAt("AvailableAmount", balance);
		
		System.out.println("***************End to call IBKE2E_GetAccountBalance **********");
		//fireExitEvent("OK");
  }
}
