package com.ibm.btt.test;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.KeyedCollection;

/**
 * Class Generated by BTT Tool Created since: 2013/02/26 11:17:26
 */
public class IBKE2E_CloseTransaction extends BTTServerOperation {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {

		KeyedCollection kc = this.getKeyedCollection();
		
		System.out.println("***************Transaction Finished**********");
		System.out.println(kc);
		
		fireExitEvent("OK");
		
	}

}
