package com.ibm.btt.test;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Hashtable;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.OperationRepliedEvent;

/**
 * Class Generated by BTT Tool Created since: 2013/01/29 14:25:03
 */
public class PrintContext extends BTTServerOperation {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {
		KeyedCollection kc = this.getKeyedCollection();

		System.out.println("##############  PrintContext "
				+ this.getKeyedCollection());
		
		System.out.println("selectedData=" + kc.getValueAt("selectedData"));
		System.out.println("selectedData2=" + kc.getValueAt("selectedData2"));
		System.out.println("selectedData3=" + kc.getValueAt("selectedData3"));
		System.out.println("selectedData4=" + kc.getValueAt("selectedData4"));

		OperationRepliedEvent event = new OperationRepliedEvent(this);
		Hashtable ht = new Hashtable();
		event.setParameters(ht);
		ht.put(com.ibm.btt.automaton.ext.DSEOperationState.EXIT_EVENT_NAME,
				"ok");

		fireHandleOperationRepliedEvent(event);
	}
}
