package com.ibm.btt.sample.operation;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
/** 
 * Class Generated by BTT Tool
 * Created since: 2010/11/30 14:37:40
 */
public class AjaxTest extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	System.out.println("AjaxTest");
  }
}
