package com.ibm.btt.sample.operation;
import com.ibm.btt.base.BTTServerOperation;
/** 
 * Class Generated by BTT Tool
 * Created since: 2011/01/05 17:13:25
 */
public class AjaxTimeOut extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
//	  System.out.println(this.getContext().getParent().getKeyedCollection().getValueAt("AjaxTimeOut"));
	  System.out.println(System.currentTimeMillis());
//	  Test Session TimeOut < Client TimeOut
	  Thread.sleep(1500);
//	  Test Session TimeOut > Client TimeOut
//	  Thread.sleep(150000);
//	  System.out.println("AjaxTimeOut");
	  System.out.println(System.currentTimeMillis());
	  this.setValueAt("name", "Liu Yuxuan");
	  this.setValueAt("password","IBM");
//	  this.setValueAt("AjaxTimeOut", "Test Ajax Time Out");
//	  System.out.println(this.getContext().getParent().getKeyedCollection());
  }
}
