package com.ibm.btt.sample.operation;
import com.ibm.btt.base.BTTServerOperation;
/** 
 * Class Generated by BTT Tool
 * Created since: 2010/11/30 14:37:40
 */
public class AjaxExceptionTest extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc --> 
 */
  public void execute() throws Exception {
	  	  setValueAt("dse_errorPage","errorpage.jsp");
		  throw new Exception();
  }
}
