package com.ibm.btt.sample.operation;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.cs.html.HtmlConstants;
/** 
 * Class Generated by BTT Tool
 * Created since: 2011/01/04 10:22:34
 */
public class GlobeEcaOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  super.execute();
	  this.getContext().setValueAt(HtmlConstants.REPLYPAGE,"globeEca.jsp");
  }
}
