package com.ibm.btt.sample.operation;
import java.math.BigDecimal;
import java.util.Random;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.DSEInvalidRequestException;
import com.ibm.btt.base.DSEObjectNotFoundException;
import com.ibm.btt.base.Hashtable;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.OperationRepliedEvent;
import com.ibm.btt.base.types.impl.Currency;
/** 
 * Class Generated by BTT Tool
 * Created since: 2010/09/21 11:00:07
 */
public class InitTableOperation extends BTTServerOperation {
	private Random rand = new Random();
	
	protected final String PAGENAME = "pageName";
	static Currency salary = null;

	/**
	 * Constructs a DisplayPageOperation.
	 */
	public InitTableOperation() {
		super();
	}

	/**
	 * Constructs a DisplayPageOperation.
	 * 
	 * @param anOperationName
	 *            java.lang.String
	 * @exception java.io.IOException
	 *                The exception description.
	 */
	public InitTableOperation(String anOperationName) throws java.io.IOException {
		super(anOperationName);
	}

	/**
	 * Constructs a DisplayPageOperation.
	 * 
	 * @param anOperationName
	 *            java.lang.String
	 * @param aParentContext
	 *            java.lang.String
	 * @exception java.io.IOException
	 *                The exception description.
	 * @exception com.ibm.dse.base.DSEObjectNotFoundException
	 *                The exception description.
	 * @exception com.ibm.dse.base.DSEInvalidRequestException
	 *                The exception description.
	 */
	public InitTableOperation(String anOperationName, String aParentContext)
			throws java.io.IOException, DSEObjectNotFoundException, DSEInvalidRequestException {
		super(anOperationName, aParentContext);
	}

	/**
	 * Constructs a DisplayPageOperation.
	 * 
	 * @param anOperationName
	 *            java.lang.String
	 * @param aParentContext
	 *            com.ibm.dse.base.Context
	 * @exception java.io.IOException
	 *                The exception description.
	 * @exception com.ibm.dse.base.DSEInvalidRequestException
	 *                The exception description.
	 */
	public InitTableOperation(String anOperationName, Context aParentContext)
			throws java.io.IOException, DSEInvalidRequestException {
		super(anOperationName, aParentContext);
	}

  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
	  System.out.println("InitTableOperation");
	  
	  KeyedCollection tableKColl = this.getContext().getKeyedCollection();
	    
	  IndexedCollection tableData = (IndexedCollection)tableKColl.getElementAt("tableData");
	  //IndexedCollection genderData = (IndexedCollection)tableKColl.getElementAt("genderComboList");
	  Currency salary = new Currency("USD",new BigDecimal(10));
//	  int salary =10;
	  
	  /*tableData.removeAll();
	  
	  tableData.createElement(arg0);
	  
	  tableData.addElement(aDataElement)*/
	  
	  tableKColl.setValueAt("genderComboList.0.labelselect", "male");
	  tableKColl.setValueAt("genderComboList.1.labelselect", "felmale");
	  for (int i = 0; i < tableData.size(); i++) {
		  tableKColl.setValueAt("tableData."+i+".index", true);
		  tableKColl.setValueAt("tableData."+i+".name", "liuyuxuan");
		  tableKColl.setValueAt("tableData."+i+".gender", "male");	

		  tableKColl.setValueAt("tableData."+i+".Num", new BigDecimal(i));
		  salary.setValue(new BigDecimal(10+i));
		  tableKColl.setValueAt("tableData."+i+".salary", salary);
		  tableKColl.setValueAt("tableData."+i+".position", "SE");
		  //tableKColl.setValueAt("tableData."+i+".birth", "Tue Sep 14 2010 00:00:00 GMT+0800");
//		  tableKColl.setValueAt("tableData."+i+".birth", "10-22-2010");
		  tableKColl.setValueAt("tableData."+i+".birth", (new java.util.Date()));
		  tableKColl.setValueAt("tableData."+i+".imageField", rand.nextBoolean()?"img/cry.jpg":"img/location.gif");
	  }

	  System.out.println(this.getContext().getKeyedCollection().getElementAt("tableData"));
	  
	  OperationRepliedEvent event = new OperationRepliedEvent(this);
	  Hashtable ht = new Hashtable();
	  event.setParameters(ht);

	  
	  ht.put(com.ibm.btt.automaton.ext.DSEOperationState.EXIT_EVENT_NAME, "ok");
	  this.fireHandleOperationRepliedEvent(event);
	  fireExitEvent("init");
  }
}
