package com.ibm.btt.sample.operation;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Constants;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2010/12/22 16:56:56
 */
public class SetStyleOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  
  KeyedCollection tableKColl = this.getContext().getKeyedCollection();
	  
	  IndexedCollection tableData = (IndexedCollection)tableKColl.getElementAt("tableData");
//	  Currency salary = new Currency("USD",new BigDecimal(10));
	  int salary =10;
	  for (int i = 0; i < tableData.size(); i++) {
		  tableKColl.setValueAt("tableData."+i+".index", true);
		  tableKColl.setValueAt("tableData."+i+".name", "BTT"+i);
		  tableKColl.setValueAt("tableData."+i+".gender", "male");
	  }
	  this.setValueAt(Constants.REPLYPAGE,"setStyle.jsp" );
  }
}
