package com.ibm.btt.sample.operation;
import java.util.Random;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.DSEInvalidRequestException;
import com.ibm.btt.base.DSEObjectNotFoundException;
import com.ibm.btt.base.Hashtable;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.OperationRepliedEvent;
import com.ibm.btt.cs.html.HtmlConstants;
/** 
 * Class Generated by BTT Tool
 * Created since: 2010/09/21 11:00:07
 */
public class TabbedPaneSelectActionOperation extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
	protected final String PAGENAME = "pageName";
	/**
	 * Constructs a DisplayPageOperation.
	 */
	public TabbedPaneSelectActionOperation() {
		super();
	}

	/**
	 * Constructs a DisplayPageOperation.
	 * 
	 * @param anOperationName
	 *            java.lang.String
	 * @exception java.io.IOException
	 *                The exception description.
	 */
	public TabbedPaneSelectActionOperation(String anOperationName) throws java.io.IOException {
		super(anOperationName);
	}

	/**
	 * Constructs a DisplayPageOperation.
	 * 
	 * @param anOperationName
	 *            java.lang.String
	 * @param aParentContext
	 *            java.lang.String
	 * @exception java.io.IOException
	 *                The exception description.
	 * @exception com.ibm.dse.base.DSEObjectNotFoundException
	 *                The exception description.
	 * @exception com.ibm.dse.base.DSEInvalidRequestException
	 *                The exception description.
	 */
	public TabbedPaneSelectActionOperation(String anOperationName, String aParentContext)
			throws java.io.IOException, DSEObjectNotFoundException, DSEInvalidRequestException {
		super(anOperationName, aParentContext);
	}

	/**
	 * Constructs a DisplayPageOperation.
	 * 
	 * @param anOperationName
	 *            java.lang.String
	 * @param aParentContext
	 *            com.ibm.dse.base.Context
	 * @exception java.io.IOException
	 *                The exception description.
	 * @exception com.ibm.dse.base.DSEInvalidRequestException
	 *                The exception description.
	 */
	public TabbedPaneSelectActionOperation(String anOperationName, Context aParentContext)
			throws java.io.IOException, DSEInvalidRequestException {
		super(anOperationName, aParentContext);
	}
	
	
  public void execute() throws Exception {
	  
	 // System.out.println(this.getContext().getKeyedCollection().getElementAt("tableData"));
	  setValueAt("userID","userID");
	  String resultPage="tabbedPane/TabbedPane03.jsp";
	  System.out.println("InitCurrencyTableOperation");
	  Random random = new Random(); 
	  KeyedCollection tableKColl = this.getContext().getKeyedCollection();
	  
	  IndexedCollection tableData = (IndexedCollection)tableKColl.getElementAt("tableData");
	  for (int i = 0; i < tableData.size(); i++) {
		  tableKColl.setValueAt("tableData."+i+".index", i);
		  tableKColl.setValueAt("tableData."+i+".cardNo", System.currentTimeMillis()+i);
		  tableKColl.setValueAt("tableData."+i+".amount", random.nextInt(20000));
	  }

	  IndexedCollection fundData = (IndexedCollection)tableKColl.getElementAt("fundtableData");
	  for (int i = 0; i < fundData.size(); i++) {
		  tableKColl.setValueAt("fundtableData."+i+".index", i);
		  tableKColl.setValueAt("fundtableData."+i+".fundNo", System.currentTimeMillis()+i);
		  tableKColl.setValueAt("fundtableData."+i+".amount", random.nextInt(20000));
	  }
	  IndexedCollection stockData = (IndexedCollection)tableKColl.getElementAt("stocktableData");
	  for (int i = 0; i < stockData.size(); i++) {
		  tableKColl.setValueAt("stocktableData."+i+".index", i);
		  tableKColl.setValueAt("stocktableData."+i+".stockNo", System.currentTimeMillis()+i);
		  tableKColl.setValueAt("stocktableData."+i+".amount", random.nextInt(50000));
	  }
      System.out.println("selectOp"+getValueAt("selectOp"));
      if ("deposit_transfer".equals(getValueAt("selectOp"))){
    	  resultPage="tabbedPane/TabbedPane05.jsp";
      }else if("open_account".equals(getValueAt("selectOp"))){
    	  resultPage="tabbedPane/TabbedPane04.jsp";
      }
    
      System.out.println(resultPage);
	  setValueAt(HtmlConstants.REPLYPAGE, resultPage);
  }
}
