package com.ibm.btt.sample.operation;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Random;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Constants;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.types.impl.Currency;
/** 
 * Class Generated by BTT Tool
 * Created since: 2010/11/30 15:44:28
 */
public class TableAlignTest extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  KeyedCollection tableKColl = this.getContext().getKeyedCollection();
	  String rad = (String)getValueAt("rad");
	  int[] ia = {2,3,10,-4,-5,-30};
	  Random rand = new Random();

	  for (int i = 0; i < 6; i++) {
		  tableKColl.setValueAt("depList."+i+".label", ia[i]);
		  tableKColl.setValueAt("depList."+i+".value", "v"+i);
		  tableKColl.setValueAt("comboList."+i+".label", ia[i]);
	  }
	  if(rad == null || !rad.equals("save")) {
		for (int i = 0; i < 6; i++) {
			tableKColl.setValueAt("tableData."+i+".tString", "SSN" + String.valueOf(rand.nextInt(99)));
			tableKColl.setValueAt("tableData."+i+".tCurrency",new Currency("USD",new BigDecimal(ia[i])));
			tableKColl.setValueAt("tableData."+i+".dateField",new Date());
			tableKColl.setValueAt("tableData."+i+".tNumber", new BigDecimal(ia[i]));
			tableKColl.setValueAt("tableData."+i+".tev", "test");
		}
	  }
	  System.out.println(this.getContext().getKeyedCollection());
	  //setValueAt(Constants.REPLYPAGE,"tableAlignTest.jsp");
	  fireExitEvent("init");
  }
}
