package com.ibm.btt.sample.operation.nls;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.cs.html.HtmlConstants;
import com.ibm.btt.nls.util.I18nResourceBundle;
import com.ibm.btt.nls.util.I18nUtil;

/** 
 * Class Generated by BTT Tool
 * Created since: 2011/02/23 16:13:25
 */
public class CheckUserNlsOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 */
 
@SuppressWarnings({ "rawtypes", "unchecked" })
public void execute() throws Exception {
	  super.execute();
	 	  
	  String result	=	"";
	  String userName	=	"";
	  String age	=	"";
	  String nlsType	=	"";
	  Map nlsMap = new HashMap();
	  List nlsList = new LinkedList();
	  Locale cn = new Locale("zh", "CN"); 
	  I18nUtil.setLocale(cn);

	  if(this.getContext().getKeyedCollection().getElementAt("username").getValue()!=null){
		  userName	=	this.getContext().getKeyedCollection().getElementAt("username").getValue().toString();
		  nlsList.add(userName);
		  nlsMap.put("name", userName);
	  }
	  
	  if(this.getContext().getKeyedCollection().getElementAt("age").getValue()!=null){
		  age	=	this.getContext().getKeyedCollection().getElementAt("age").getValue().toString();
		  nlsList.add(age);
		  nlsMap.put("age", age);
	  }
	  
	  if(this.getContext().getKeyedCollection().getElementAt("nlsType").getValue()!=null){
		  nlsType	=	this.getContext().getKeyedCollection().getElementAt("nlsType").getValue().toString();
	  }
	
	  if(nlsType.equals("key")){
		  result = I18nUtil.getI18nString("%nls.NLSErrorMessage/NONE");
	  }
	  else if(nlsType.equals("list")){//[]
		  result = I18nUtil.getI18nString("%nls.BTTResource/I18N_MESSAGE", nlsList);//result is differnt as map type
		  System.out.println(result);
	  }
	  else if(nlsType.equals("map")){//map
		  result = I18nUtil.getI18nString("%nls.BTTResource/I18N_MESSAGE",nlsMap);
		  System.out.println(result);
	  }
	  else if(nlsType.equals("params")){//map
		  result = I18nUtil.getI18nString("%nls.BTTResource/I18N_MESSAGE",userName,age);
		  System.out.println(result);
	  }
	  
	  
	  this.setValueAt("nlsResult", result);
	  this.setValueAt(HtmlConstants.REPLYPAGE, "nls/checkUserNls.jsp");
	  
  }
}
